Repository streetsidesoftware/cspell, pull requests merged in 2021-09, with the labels that each got.

#1623 docs: lint - clean up README
  README.md
Labels: Documentation

#1622 docs: Add Hunspell to the list of packages.
  README.md
Labels: Documentation

#1624 dev: Update Dutch Dictionary
  packages/cspell-lib/package-lock.json
  packages/cspell-lib/package.json
  packages/cspell-lib/samples/Dutch.txt
Labels: fix

#1633 fix: Upgrade British English dictionary to v2.
  packages/cspell-bundled-dicts/package-lock.json
  packages/cspell-bundled-dicts/package.json
Labels: fix

#1639 fix: Perf - Try improving suggestion performance.
  packages/cspell-lib/src/util/MinHeapQueue.test.ts
  packages/cspell-lib/src/util/MinHeapQueue.ts
  packages/cspell-lib/src/util/PairingHeap.test.ts
  packages/cspell-lib/src/util/PairingHeap.ts
  packages/cspell-lib/src/util/wordSplitter.ts
  packages/cspell-trie-lib/src/lib/PairingHeap.test.ts
  packages/cspell-trie-lib/src/lib/PairingHeap.ts
  packages/cspell-trie-lib/src/lib/orthography.ts
  packages/cspell-trie-lib/src/lib/suggest-en-a-star.test.ts
  packages/cspell-trie-lib/src/lib/suggest.ts
  packages/cspell-trie-lib/src/lib/suggestAStar.test.ts
  packages/cspell-trie-lib/src/lib/suggestAStar.ts
Labels: fix

#1640 fix: Fix version number reference
  docs/configuration/index.md
  packages/cspell/README.md
Labels: Documentation, fix

#1644 dev: Some fixes to the A* Suggestion generator
  packages/cspell-lib/src/SpellingDictionary/SpellingDictionaryMethods.ts
  packages/cspell-trie-lib/src/lib/suggest-en-a-star.test.ts
  packages/cspell-trie-lib/src/lib/suggest.ts
  packages/cspell-trie-lib/src/lib/suggestAStar.test.ts
  packages/cspell-trie-lib/src/lib/suggestAStar.ts
Labels: fix

#1645 dev: Make sure natural compound words are tested.
  packages/cspell-trie-lib/src/lib/suggestAStar.test.ts
  packages/cspell-trie-lib/src/lib/suggestAStar.ts
Labels: fix

#1657 dev: Refactor Suggestion Collector into its own file.
  packages/cspell-trie-lib/src/lib/index.ts
  packages/cspell-trie-lib/src/lib/suggest-en-a-star.test.ts
  packages/cspell-trie-lib/src/lib/suggest-en.test.ts
  packages/cspell-trie-lib/src/lib/suggest.legacy.test.ts
  packages/cspell-trie-lib/src/lib/suggest.test.ts
  packages/cspell-trie-lib/src/lib/suggest.ts
  packages/cspell-trie-lib/src/lib/suggestAStar.test.ts
  packages/cspell-trie-lib/src/lib/suggestAStar.ts
  packages/cspell-trie-lib/src/lib/suggestCollector.test.ts
  packages/cspell-trie-lib/src/lib/suggestCollector.ts
  packages/cspell-trie-lib/src/lib/trie.test.ts
  packages/cspell-trie-lib/src/lib/trie.ts
Labels: fix

#1662 dev: fix add a timeout to generating suggestions.
  packages/cspell-trie-lib/src/lib/SimpleDictionaryParser.test.ts
  packages/cspell-trie-lib/src/lib/genSuggestionsOptions.ts
  packages/cspell-trie-lib/src/lib/suggest-en-a-star.test.ts
  packages/cspell-trie-lib/src/lib/suggest-en.test.ts
  packages/cspell-trie-lib/src/lib/suggest-es.test.ts
  packages/cspell-trie-lib/src/lib/suggest-nl.test.ts
  packages/cspell-trie-lib/src/lib/suggest.legacy.test.ts
  packages/cspell-trie-lib/src/lib/suggest.test.ts
  packages/cspell-trie-lib/src/lib/suggest.ts
  packages/cspell-trie-lib/src/lib/suggestAStar.test.ts
  packages/cspell-trie-lib/src/lib/suggestAStar.ts
  packages/cspell-trie-lib/src/lib/suggestCollector.test.ts
  packages/cspell-trie-lib/src/lib/suggestCollector.ts
  packages/cspell-trie-lib/src/lib/timer.ts
  packages/cspell-trie-lib/src/lib/trie.test.ts
  packages/cspell-trie-lib/src/lib/trie.ts
Labels: fix

#1663 dev: Move CheckFailed Error into its own file.
  packages/cspell/bin.js
  packages/cspell/src/app.ts
  packages/cspell/src/util/errors.test.ts
  packages/cspell/src/util/errors.ts
Labels: fix

#1665 test: fix github-actions
  .github/workflows/test.yml
Labels: fix, test

#1664 dev: Test time limits on suggestions.
  packages/cspell-trie-lib/src/lib/suggest-en-a-star.test.ts
  packages/cspell-trie-lib/src/lib/suggest-en.test.ts
  packages/cspell-trie-lib/src/lib/suggest.legacy.test.ts
  packages/cspell-trie-lib/src/lib/suggest.test.ts
  packages/cspell-trie-lib/src/lib/suggest.ts
  packages/cspell-trie-lib/src/lib/suggestAStar.ts
  packages/cspell-trie-lib/src/lib/suggestCollector.ts
Labels: fix

#1667 ci: Use caching to speed up github actions
  .github/workflows/test.yml
Labels: chore

#1668 fix: Support Suggestion timeouts
  cspell.schema.json
  packages/cspell-lib/src/Settings/DefaultSettings.ts
  packages/cspell-lib/src/SpellingDictionary/SpellingDictionary.ts
  packages/cspell-lib/src/SpellingDictionary/SpellingDictionaryCollection.ts
  packages/cspell-lib/src/SpellingDictionary/SpellingDictionaryFromTrie.ts
  packages/cspell-lib/src/SpellingDictionary/SpellingDictionaryMethods.ts
  packages/cspell-lib/src/validator.ts
  packages/cspell-trie-lib/src/lib/suggest-en-a-star.test.ts
  packages/cspell-trie-lib/src/lib/suggest-en.test.ts
  packages/cspell-trie-lib/src/lib/suggest.test.ts
  packages/cspell-trie-lib/src/lib/suggest.ts
  packages/cspell-trie-lib/src/lib/suggestAStar.test.ts
  packages/cspell-trie-lib/src/lib/suggestAStar.ts
  packages/cspell-trie-lib/src/lib/suggestCollector.test.ts
  packages/cspell-trie-lib/src/lib/suggestCollector.ts
  packages/cspell-trie-lib/src/lib/trie.test.ts
  packages/cspell-types/cspell.schema.json
  packages/cspell-types/src/settings/CSpellSettingsDef.ts
Labels: fix

#1669 fix: sample more often to make sure the suggest stops on time.
  packages/cspell-trie-lib/src/lib/suggestAStar.ts
Labels: fix

#1670 docs: Rebuild docs
  docs/types/.cspell.json
  docs/types/cspell-types/interfaces/BaseSetting.md
  docs/types/cspell-types/interfaces/CSpellSettings.md
  docs/types/cspell-types/interfaces/CSpellSettingsWithSourceTrace.md
  docs/types/cspell-types/interfaces/DictionaryDefinitionAlternate.md
  docs/types/cspell-types/interfaces/DictionaryDefinitionBase.md
  docs/types/cspell-types/interfaces/DictionaryDefinitionCustom.md
  docs/types/cspell-types/interfaces/DictionaryDefinitionPreferred.md
  docs/types/cspell-types/interfaces/ExtendableSettings.md
  docs/types/cspell-types/interfaces/FileSettings.md
  docs/types/cspell-types/interfaces/FileSource.md
  docs/types/cspell-types/interfaces/ImportFileRef.md
  docs/types/cspell-types/interfaces/InMemorySource.md
  docs/types/cspell-types/interfaces/LanguageSetting.md
  docs/types/cspell-types/interfaces/LanguageSettingFilterFields.md
  docs/types/cspell-types/interfaces/LanguageSettingFilterFieldsDeprecated.md
  docs/types/cspell-types/interfaces/LanguageSettingFilterFieldsPreferred.md
  docs/types/cspell-types/interfaces/LegacySettings.md
  docs/types/cspell-types/interfaces/MergeSource.md
  docs/types/cspell-types/interfaces/OverrideFilterFields.md
  docs/types/cspell-types/interfaces/OverrideSettings.md
  docs/types/cspell-types/interfaces/PnPSettings.md
  docs/types/cspell-types/interfaces/RegExpPatternDefinition.md
  docs/types/cspell-types/interfaces/ReportingConfiguration.md
  docs/types/cspell-types/interfaces/Settings.md
  docs/types/cspell-types/interfaces/SuggestionsConfiguration.md
  docs/types/cspell-types/interfaces/WorkspaceTrustSettings.md
  docs/types/cspell-types/modules.md
Labels: Documentation

#1674 fix: Fix suggestions when working with case aware dictionaries.
  packages/cspell-trie-lib/.vscode/launch.json
  packages/cspell-trie-lib/src/lib/SimpleDictionaryParser.test.ts
  packages/cspell-trie-lib/src/lib/SimpleDictionaryParser.ts
  packages/cspell-trie-lib/src/lib/genSuggestionsOptions.ts
  packages/cspell-trie-lib/src/lib/suggest-en-a-star.test.ts
  packages/cspell-trie-lib/src/lib/suggest-nl.test.ts
  packages/cspell-trie-lib/src/lib/suggest.legacy.test.ts
  packages/cspell-trie-lib/src/lib/suggest.test.ts
  packages/cspell-trie-lib/src/lib/suggest.ts
  packages/cspell-trie-lib/src/lib/suggestAStar.test.ts
  packages/cspell-trie-lib/src/lib/suggestAStar.ts
  packages/cspell-trie-lib/src/lib/suggestCollector.ts
  packages/cspell-trie-lib/src/lib/trie.ts
  packages/cspell-trie-lib/src/lib/util.ts
  packages/cspell-trie-lib/src/lib/walker.test.ts
  packages/cspell-trie-lib/src/lib/walker.ts
Labels: fix

#1677 fix: drop need for iconv-lite and iterable-to-stream
  packages/cspell-bundled-dicts/package.json
  packages/cspell-dynamic-loader/package.json
  packages/cspell-glob/package.json
  packages/cspell-io/package-lock.json
  packages/cspell-io/package.json
  packages/cspell-io/src/async/asyncIterable.test.ts
  packages/cspell-io/src/file/fileReader.test.ts
  packages/cspell-io/src/file/fileReader.ts
  packages/cspell-io/src/file/fileWriter.ts
  packages/cspell-io/src/index.test.ts
  packages/cspell-lib/package.json
  packages/cspell-tools/package.json
  packages/cspell-trie-lib/package.json
  packages/cspell-trie/package-lock.json
  packages/cspell-trie/package.json
  packages/cspell-trie/src/app.ts
  packages/cspell-trie2-lib/package.json
  packages/cspell-types/package.json
  packages/cspell/package.json
  packages/hunspell-reader/package.json
  test-packages/test-cspell-io/src/index.ts
Labels: fix

#1678 fix: Change the suggestions to not include ties by default.
  packages/cspell-lib/src/SpellingDictionary/SpellingDictionary.ts
  packages/cspell-lib/src/__snapshots__/validator.test.ts.snap
  packages/cspell-lib/src/validator.ts
  packages/cspell-trie-lib/src/lib/genSuggestionsOptions.ts
  packages/cspell-trie-lib/src/lib/suggest.ts
  packages/cspell-trie-lib/src/lib/suggestAStar.ts
  packages/cspell-trie-lib/src/lib/suggestCollector.ts
Labels: fix

#1679 ci: Remove `.tsbuildinfo` during clean
  integration-tests/package.json
  package.json
  packages/cspell-dynamic-loader/package.json
  packages/cspell-glob/package.json
  packages/cspell-io/package.json
  packages/cspell-lib/package.json
  packages/cspell-tools/package.json
  packages/cspell-trie-lib/package.json
  packages/cspell-trie/package.json
  packages/cspell-trie2-lib/package.json
  packages/cspell-types/package.json
  packages/cspell/package.json
  packages/hunspell-reader/package.json
  test-packages/test-cspell-glob/package.json
  test-packages/test-cspell-io/package.json
  test-packages/test-cspell-lib-webpack/package.json
  test-packages/test-cspell-lib/package.json
  test-packages/test-cspell-tools/package.json
  test-packages/test-cspell/package.json
Labels: chore

#1666 Revert "test: fix github-actions (#1665)"
  .github/workflows/test.yml
Labels: fix

#1683 ci: Improve the development experience
  .gitignore
  integration-tests/package.json
  integration-tests/tsconfig.dev.json
  package.json
  packages/cspell-bundled-dicts/cspell.json
  packages/cspell-bundled-dicts/package.json
  packages/cspell-bundled-dicts/tsconfig.dev.json
  packages/cspell-bundled-dicts/tsconfig.json
  packages/cspell-dynamic-loader/package.json
  packages/cspell-dynamic-loader/tsconfig.dev.json
  packages/cspell-glob/.npmignore
  packages/cspell-glob/package.json
  packages/cspell-glob/tsconfig.dev.json
  packages/cspell-io/.npmignore
  packages/cspell-io/package.json
  packages/cspell-io/tsconfig.dev.json
  packages/cspell-lib/.npmignore
  packages/cspell-lib/package.json
  packages/cspell-lib/tsconfig.dev.json
  packages/cspell-tools/.npmignore
  packages/cspell-tools/cSpell.json
  packages/cspell-tools/package.json
  packages/cspell-tools/tsconfig.dev.json
  packages/cspell-trie-lib/.npmignore
  packages/cspell-trie-lib/cspell.json
  packages/cspell-trie-lib/package.json
  packages/cspell-trie-lib/tsconfig.dev.json
  packages/cspell-trie/.npmignore
  packages/cspell-trie/package.json
  packages/cspell-trie/tsconfig.dev.json
  packages/cspell-trie2-lib/.npmignore
  packages/cspell-trie2-lib/package.json
  packages/cspell-trie2-lib/tsconfig.dev.json
  packages/cspell-types/package.json
  packages/cspell-types/tsconfig.dev.json
  packages/cspell/.npmignore
  packages/cspell/package.json
  packages/cspell/tsconfig.dev.json
  packages/hunspell-reader/.gitignore
  packages/hunspell-reader/.npmignore
  packages/hunspell-reader/cSpell.json
  packages/hunspell-reader/package.json
  packages/hunspell-reader/tsconfig.dev.json
  test-packages/cspell-cli/tsconfig.dev.json
  test-packages/test-cspell-glob/package.json
  test-packages/test-cspell-glob/tsconfig.dev.json
  test-packages/test-cspell-io/package.json
  test-packages/test-cspell-io/tsconfig.dev.json
  test-packages/test-cspell-lib-webpack/package.json
  test-packages/test-cspell-lib-webpack/tsconfig.dev.json
  test-packages/test-cspell-lib/package.json
  test-packages/test-cspell-lib/tsconfig.dev.json
  test-packages/test-cspell-tools/cspell.json
  test-packages/test-cspell-tools/cspell.test.json
  test-packages/test-cspell-tools/package.json
  test-packages/test-cspell-tools/tsconfig.dev.json
  test-packages/test-cspell/package.json
  test-packages/test-cspell/tsconfig.dev.json
  tsconfig.json
Labels: chore

#1686 fix: Delete .pre-commit-hooks.yaml
  .pre-commit-hooks.yaml
Labels: fix

#1688 refactor: imports of `cspell-types` should be type only
  cspell.code-workspace
  packages/cspell-json-reporter/package.json
  packages/cspell-json-reporter/src/CSpellJSONReporterOutput.ts
  packages/cspell-json-reporter/src/index.test.ts
  packages/cspell-json-reporter/tsconfig.dev.json
  packages/cspell-json-reporter/tsconfig.json
  packages/cspell-lib/src/Settings/CSpellSettingsServer.test.ts
  packages/cspell-lib/src/Settings/CSpellSettingsServer.ts
  packages/cspell-lib/src/Settings/DefaultSettings.ts
  packages/cspell-lib/src/Settings/DictionaryReferenceCollection.ts
  packages/cspell-lib/src/Settings/DictionarySettings.test.ts
  packages/cspell-lib/src/Settings/DictionarySettings.ts
  packages/cspell-lib/src/Settings/GlobalSettings.ts
  packages/cspell-lib/src/Settings/InDocSettings.ts
  packages/cspell-lib/src/Settings/LanguageSettings.test.ts
  packages/cspell-lib/src/Settings/LanguageSettings.ts
  packages/cspell-lib/src/Settings/RegExpPatterns.test.ts
  packages/cspell-lib/src/Settings/TextDocumentSettings.ts
  packages/cspell-lib/src/Settings/index.ts
  packages/cspell-lib/src/Settings/link.ts
  packages/cspell-lib/src/SpellingDictionary/Dictionaries.test.ts
  packages/cspell-lib/src/SpellingDictionary/Dictionaries.ts
  packages/cspell-lib/src/SpellingDictionary/DictionaryLoader.ts
  packages/cspell-lib/src/SpellingDictionary/SpellingDictionary.ts
  packages/cspell-lib/src/exclusionHelper.test.ts
  packages/cspell-lib/src/exclusionHelper.ts
  packages/cspell-lib/src/spellCheckFile.test.ts
  packages/cspell-lib/src/spellCheckFile.ts
  packages/cspell-lib/src/textValidator.ts
  packages/cspell-lib/src/trace.test.ts
  packages/cspell-lib/src/trace.ts
  packages/cspell-lib/src/util/repMap.ts
  packages/cspell-lib/src/util/text.test.ts
  packages/cspell-lib/src/util/text.ts
  packages/cspell-lib/src/util/wordSplitter.test.ts
  packages/cspell-lib/src/util/wordSplitter.ts
  packages/cspell-lib/src/validator.test.ts
  packages/cspell-lib/src/validator.ts
  packages/cspell/src/CSpellApplicationConfiguration.ts
  packages/cspell/src/application.test.ts
  packages/cspell/src/application.ts
  packages/cspell/src/cli-reporter.ts
  packages/cspell/src/index.ts
  packages/cspell/src/lint.ts
  packages/cspell/src/util/InMemoryReporter.ts
  packages/cspell/src/util/__snapshots__/reporters.test.ts.snap
  packages/cspell/src/util/glob.ts
  packages/cspell/src/util/reporters.test.ts
  packages/cspell/src/util/reporters.ts
  test-packages/test-cspell/src/index.ts
Labels: fix

#1702 fix: Fix accidental promise returned by reporters.
  packages/cspell/src/util/reporters.ts
Labels: fix

#1710 fix: Make dict-en-gb version 2 optional because of license.
  integration-tests/package-lock.json
  packages/cspell-bundled-dicts/package-lock.json
  packages/cspell-bundled-dicts/package.json
  packages/cspell-dynamic-loader/package-lock.json
  packages/cspell-glob/package-lock.json
  packages/cspell-io/package-lock.json
  packages/cspell-json-reporter/package-lock.json
  packages/cspell-lib/package-lock.json
  packages/cspell-tools/package-lock.json
  packages/cspell-trie-lib/package-lock.json
  packages/cspell-trie/package-lock.json
  packages/cspell-trie2-lib/package-lock.json
  packages/cspell-types/package-lock.json
  packages/cspell/package-lock.json
  packages/hunspell-reader/package-lock.json
  test-packages/test-cspell-lib-webpack/package-lock.json
Labels: fix

#1712 fix: Roll back update to `@cspell/dict-en-gb@2`
  packages/cspell-bundled-dicts/package-lock.json
  packages/cspell-bundled-dicts/package.json
Labels: fix

#1714 fix: Use process directly instead of importing it.
  packages/cspell-trie-lib/src/lib/timer.test.ts
  packages/cspell-trie-lib/src/lib/timer.ts
Labels: fix

#1731 ci: Disable Coveralls - their API has been down for a couple of days.
  .github/workflows/coverage.yml
Labels: chore

#1730 fix: Allow config file version to be a number.
  packages/cspell-lib/src/Settings/CSpellSettingsServer.test.ts
  packages/cspell-lib/src/Settings/CSpellSettingsServer.ts
  test-fixtures/issues/issue-1729/a.yaml
  test-fixtures/issues/issue-1729/b.yaml
Labels: fix

#1743 fix: Improve Patterns and RegExp handling
  cspell-dict.txt
  packages/cspell-lib/src/Settings/CSpellSettingsServer.ts
  packages/cspell-lib/src/Settings/InDocSettings.test.ts
  packages/cspell-lib/src/Settings/patterns.test.ts
  packages/cspell-lib/src/Settings/patterns.ts
  packages/cspell-lib/src/util/text.test.ts
  packages/cspell-lib/src/util/text.ts
Labels: fix

#1744 dev: Update German dictionary in integration tests
  integration-tests/package-lock.json
  integration-tests/package.json
  integration-tests/snapshots/MartinThoma/LaTeX-examples/snapshot.txt
Labels: fix

#1745 fix: Patterns - only add `u` if no flags are given
  packages/cspell-lib/src/Settings/InDocSettings.test.ts
  packages/cspell-lib/src/util/text.test.ts
  packages/cspell-lib/src/util/text.ts
Labels: fix

#1749 dev: change the integration report format
  integration-tests/snapshots/AdaDoom3/AdaDoom3/report.yaml
  integration-tests/snapshots/MartinThoma/LaTeX-examples/report.yaml
  integration-tests/snapshots/TheAlgorithms/Python/report.yaml
  integration-tests/snapshots/alexiosc/megistos/report.yaml
  integration-tests/snapshots/django/django/report.yaml
  integration-tests/snapshots/googleapis/google-cloud-cpp/report.yaml
  integration-tests/snapshots/mdx-js/mdx/report.yaml
  integration-tests/snapshots/microsoft/TypeScript-Website/report.yaml
  integration-tests/snapshots/php/php-src/report.yaml
  integration-tests/snapshots/pycontribs/jira/report.yaml
  integration-tests/snapshots/typescript-cheatsheets/react/report.yaml
  integration-tests/src/reporter/reportGenerator.test.ts
  integration-tests/src/reporter/reportGenerator.ts
Labels: fix

#1762 ci: Support Manual Integration Test runs
  .github/workflows/integration-test.yml
Labels: chore

#1764 ci: Try caching integration test runs to avoid repeat runs.
  .github/workflows/integration-test.yml
Labels: chore

#1766 ci: Use individual integration test repo info for hash
  .github/workflows/integration-test.yml
Labels: chore

#1767 ci: Use only the integration commit for the repo hash
  .github/workflows/integration-test.yml
Labels: chore

#1769 ci: cache integration test repo files
  .github/workflows/integration-test.yml
Labels: chore

#1768 ci: Try to speed up `npm install`
  package.json
  packages/cspell-bundled-dicts/.gitignore
  packages/cspell-bundled-dicts/cspell-default.config.js
  packages/cspell-bundled-dicts/package.json
  packages/cspell-dynamic-loader/package.json
  packages/hunspell-reader/package.json
  test-packages/yarn2/package.json
Labels: chore

#1773 fix: Display filenames instead of URI's
  integration-tests/snapshots/php/php-src/snapshot.txt
  integration-tests/src/check.ts
  packages/cspell/src/cli-reporter.ts
Labels: fix

#1774 fix: Ensure cli-reporter displays the correct message.
  integration-tests/snapshots/MartinThoma/LaTeX-examples/snapshot.txt
  integration-tests/snapshots/django/django/snapshot.txt
  integration-tests/snapshots/mdx-js/mdx/snapshot.txt
  packages/cspell-trie-lib/src/lib/suggest-en-a-star.test.ts
  packages/cspell/src/cli-reporter.test.ts
  packages/cspell/src/cli-reporter.ts
Labels: fix

#1763 feat: add --cache option to lint only changed files
  .gitignore
  package.json
  packages/cspell-json-reporter/src/__snapshots__/index.test.ts.snap
  packages/cspell-json-reporter/src/index.test.ts
  packages/cspell-types/src/CSpellReporter.ts
  packages/cspell/package-lock.json
  packages/cspell/package.json
  packages/cspell/src/__snapshots__/app.test.ts.snap
  packages/cspell/src/app.ts
  packages/cspell/src/cli-reporter.test.ts
  packages/cspell/src/fileHelper.ts
  packages/cspell/src/lint.ts
  packages/cspell/src/options.ts
  packages/cspell/src/util/__snapshots__/reporters.test.ts.snap
  packages/cspell/src/util/cache/DiskCache.test.ts
  packages/cspell/src/util/cache/DiskCache.ts
  packages/cspell/src/util/cache/DummyCache.ts
  packages/cspell/src/util/cache/getConfigHash.test.ts
  packages/cspell/src/util/cache/getConfigHash.ts
  packages/cspell/src/util/cache/hash.ts
  packages/cspell/src/util/cache/index.ts
  packages/cspell/src/util/glob.ts
  packages/cspell/src/util/reporters.test.ts
  packages/cspell/src/util/timer.ts
Labels: enhancement

#1778 fix: Update Python dictionary
  integration-tests/snapshots/TheAlgorithms/Python/report.yaml
  integration-tests/snapshots/TheAlgorithms/Python/snapshot.txt
  integration-tests/snapshots/django/django/report.yaml
  integration-tests/snapshots/django/django/snapshot.txt
  integration-tests/snapshots/pycontribs/jira/report.yaml
  integration-tests/snapshots/pycontribs/jira/snapshot.txt
  packages/cspell-bundled-dicts/package-lock.json
  packages/cspell-bundled-dicts/package.json
  packages/cspell-lib/package-lock.json
  packages/cspell-lib/package.json
Labels: fix

#1779 dev: Do not spell check generated files.
  cspell-dict.txt
  cspell.json
  integration-tests/snapshots/mdx-js/mdx/report.yaml
  integration-tests/snapshots/mdx-js/mdx/snapshot.txt
  packages/cspell-lib/samples/ruby/Gemfile
  packages/cspell-lib/src/LanguageIds.test.ts
  packages/cspell-lib/src/LanguageIds.ts
  packages/cspell-lib/src/spellCheckFile.test.ts
  packages/cspell-lib/src/spellCheckFile.ts
Labels: fix

#1782 ci: Update cspell-action.yml
  .github/workflows/cspell-action.yml
Labels: chore

#1798 test: Update suggest-en.test.ts
  packages/cspell-trie-lib/src/lib/suggest-en.test.ts
Labels: test

#1799 ci: Update Gemfile.lock
  docs/Gemfile.lock
Labels: chore

#1800 fix: Reduce the cost of regexp exclusions
  packages/cspell-lib/src/spellCheckFile.test.ts
  packages/cspell-lib/src/textValidator.ts
  packages/cspell-lib/src/util/TextRange.regexp.test.ts
  packages/cspell-lib/src/util/TextRange.test.ts
  packages/cspell-lib/src/util/TextRange.ts
  test-fixtures/issues/issue-1775/README.md
  test-fixtures/issues/issue-1775/cspell.json
  test-fixtures/issues/issue-1775/hunspell/utf_info.hxx
Labels: fix

#1811 fix: Move `@types` dependencies to dev
  .github/release-drafter.yml
  packages/cspell/package-lock.json
  packages/cspell/package.json
Labels: fix
