Repository streetsidesoftware/cspell, pull requests merged in 2022-01, with the labels that each got.

#2160 fix: Invalidate cache when config has changed
  packages/cspell-lib/src/Settings/CSpellSettingsServer.test.ts
  packages/cspell-lib/src/Settings/CSpellSettingsServer.ts
  packages/cspell-lib/src/Settings/DictionarySettings.ts
  packages/cspell-lib/src/SpellingDictionary/Dictionaries.test.ts
  packages/cspell-lib/src/SpellingDictionary/Dictionaries.ts
  packages/cspell/.vscode/launch.json
  packages/cspell/cSpell.json
  packages/cspell/src/lint/lint.ts
  packages/cspell/src/util/cache/CSpellLintResultCache.ts
  packages/cspell/src/util/cache/DiskCache.test.ts
  packages/cspell/src/util/cache/DiskCache.ts
Labels: fix

#2173 fix: Update dictionaries
  integration-tests/snapshots/MartinThoma/LaTeX-examples/report.yaml
  integration-tests/snapshots/MartinThoma/LaTeX-examples/snapshot.txt
  integration-tests/snapshots/TheAlgorithms/Python/report.yaml
  integration-tests/snapshots/TheAlgorithms/Python/snapshot.txt
  integration-tests/snapshots/django/django/report.yaml
  integration-tests/snapshots/django/django/snapshot.txt
  packages/cspell-bundled-dicts/package-lock.json
  packages/cspell-bundled-dicts/package.json
Labels: fix

#2181 chore: Update cspell-action
  .github/workflows/cspell-action.yml
Labels: chore

#2184 feat: Add support for cache options in config files.
  cspell.json
  cspell.schema.json
  packages/cspell-json-reporter/src/__snapshots__/index.test.ts.snap
  packages/cspell-json-reporter/src/index.test.ts
  packages/cspell-lib/src/Settings/CSpellSettingsServer.test.ts
  packages/cspell-lib/src/Settings/CSpellSettingsServer.ts
  packages/cspell-lib/src/Settings/GlobalSettings.test.ts
  packages/cspell-lib/src/util/logger.test.ts
  packages/cspell-types/cspell.schema.json
  packages/cspell-types/src/CSpellReporter.ts
  packages/cspell-types/src/CSpellSettingsDef.ts
  packages/cspell-types/src/configFields.ts
  packages/cspell-types/src/index.ts
  packages/cspell/README.md
  packages/cspell/cspell.json
  packages/cspell/fixtures/features/cached/README.md
  packages/cspell/fixtures/features/cached/code.ts
  packages/cspell/fixtures/features/cached/cspell.json
  packages/cspell/src/__snapshots__/app.test.ts.snap
  packages/cspell/src/app.test.ts
  packages/cspell/src/application.test.ts
  packages/cspell/src/commandLint.ts
  packages/cspell/src/lint/lint.test.ts
  packages/cspell/src/lint/lint.ts
  packages/cspell/src/options.ts
  packages/cspell/src/util/__snapshots__/reporters.test.ts.snap
  packages/cspell/src/util/cache/CacheOptions.ts
  packages/cspell/src/util/cache/DiskCache.test.ts
  packages/cspell/src/util/cache/DiskCache.ts
  packages/cspell/src/util/cache/createCache.test.ts
  packages/cspell/src/util/cache/createCache.ts
  packages/cspell/src/util/cache/index.ts
  packages/cspell/src/util/errors.ts
  packages/cspell/src/util/reporters.test.ts
Labels: feature

#2185 ci: Add integration test for apollo-server
  integration-tests/config/config.json
  integration-tests/snapshots/apollographql/apollo-server/snapshot.txt
Labels: chore

#2187 ci: for integration tests, make `**` the default
  integration-tests/config/config.json
  integration-tests/snapshots/apollographql/apollo-server/snapshot.txt
  integration-tests/snapshots/shoelace-style/shoelace/snapshot.txt
  integration-tests/src/config.ts
Labels: chore

#2188 ci: Update the list of integrations to be checked.
  .github/workflows/integration-test.yml
  cspell.code-workspace
  integration-tests/repo-list.sh
Labels: chore

#2190 doc: Update cspell-types docs
  docs/types/cspell-types/interfaces/BaseSetting.md
  docs/types/cspell-types/interfaces/CSpellReporter.md
  docs/types/cspell-types/interfaces/CSpellReporterModule.md
  docs/types/cspell-types/interfaces/CSpellSettings.md
  docs/types/cspell-types/interfaces/CSpellSettingsWithSourceTrace.md
  docs/types/cspell-types/interfaces/CacheSettings.md
  docs/types/cspell-types/interfaces/CommandLineSettings.md
  docs/types/cspell-types/interfaces/DictionaryDefinitionAlternate.md
  docs/types/cspell-types/interfaces/DictionaryDefinitionBase.md
  docs/types/cspell-types/interfaces/DictionaryDefinitionCustom.md
  docs/types/cspell-types/interfaces/DictionaryDefinitionPreferred.md
  docs/types/cspell-types/interfaces/ExtendableSettings.md
  docs/types/cspell-types/interfaces/FileSettings.md
  docs/types/cspell-types/interfaces/FileSource.md
  docs/types/cspell-types/interfaces/ImportFileRef.md
  docs/types/cspell-types/interfaces/InMemorySource.md
  docs/types/cspell-types/interfaces/Issue.md
  docs/types/cspell-types/interfaces/LanguageSetting.md
  docs/types/cspell-types/interfaces/LanguageSettingFilterFields.md
  docs/types/cspell-types/interfaces/LanguageSettingFilterFieldsDeprecated.md
  docs/types/cspell-types/interfaces/LanguageSettingFilterFieldsPreferred.md
  docs/types/cspell-types/interfaces/LegacySettings.md
  docs/types/cspell-types/interfaces/MergeSource.md
  docs/types/cspell-types/interfaces/OverrideFilterFields.md
  docs/types/cspell-types/interfaces/OverrideSettings.md
  docs/types/cspell-types/interfaces/PnPSettings.md
  docs/types/cspell-types/interfaces/ProgressFileComplete.md
  docs/types/cspell-types/interfaces/RegExpPatternDefinition.md
  docs/types/cspell-types/interfaces/ReportingConfiguration.md
  docs/types/cspell-types/interfaces/RunResult.md
  docs/types/cspell-types/interfaces/Settings.md
  docs/types/cspell-types/interfaces/SuggestionsConfiguration.md
  docs/types/cspell-types/interfaces/TextDocumentOffset.md
  docs/types/cspell-types/interfaces/TextOffset.md
  docs/types/cspell-types/interfaces/WorkspaceTrustSettings.md
  docs/types/cspell-types/modules.md
Labels: Documentation

#2227 ci: Integration - remove repo-by-repo updates
  .github/workflows/integration-test.yml
Labels: chore

#2191 fix: Fix type for some older TypeScript parsers.
  cspell.schema.json
  packages/cspell-types/cspell.schema.json
  packages/cspell-types/src/CSpellSettingsDef.ts
  packages/cspell-types/src/index.ts
Labels: fix

#2229 fix: Fix backwards compatibility for Reporters
  packages/cspell-types/src/CSpellReporter.ts
  packages/cspell/src/lint/lint.ts
Labels: fix

#2237 fix: Fix issue with `maxDuplicateProblems` setting
  integration-tests/snapshots/AdaDoom3/AdaDoom3/report.yaml
  integration-tests/snapshots/AdaDoom3/AdaDoom3/snapshot.txt
  integration-tests/snapshots/Azure/azure-rest-api-specs/snapshot.txt
  integration-tests/snapshots/MartinThoma/LaTeX-examples/report.yaml
  integration-tests/snapshots/MartinThoma/LaTeX-examples/snapshot.txt
  integration-tests/snapshots/TheAlgorithms/Python/report.yaml
  integration-tests/snapshots/TheAlgorithms/Python/snapshot.txt
  integration-tests/snapshots/alexiosc/megistos/report.yaml
  integration-tests/snapshots/alexiosc/megistos/snapshot.txt
  integration-tests/snapshots/django/django/report.yaml
  integration-tests/snapshots/django/django/snapshot.txt
  integration-tests/snapshots/googleapis/google-cloud-cpp/report.yaml
  integration-tests/snapshots/googleapis/google-cloud-cpp/snapshot.txt
  integration-tests/snapshots/graphql/graphql-spec/snapshot.txt
  integration-tests/snapshots/liriliri/licia/snapshot.txt
  integration-tests/snapshots/mdx-js/mdx/report.yaml
  integration-tests/snapshots/mdx-js/mdx/snapshot.txt
  integration-tests/snapshots/microsoft/TypeScript-Website/report.yaml
  integration-tests/snapshots/microsoft/TypeScript-Website/snapshot.txt
  integration-tests/snapshots/pagekit/pagekit/report.yaml
  integration-tests/snapshots/pagekit/pagekit/snapshot.txt
  integration-tests/snapshots/php/php-src/report.yaml
  integration-tests/snapshots/php/php-src/snapshot.txt
  integration-tests/snapshots/pycontribs/jira/report.yaml
  integration-tests/snapshots/pycontribs/jira/snapshot.txt
  integration-tests/snapshots/typescript-cheatsheets/react/report.yaml
  integration-tests/snapshots/typescript-cheatsheets/react/snapshot.txt
  packages/cspell-lib/src/textValidator.test.ts
  packages/cspell-lib/src/textValidator.ts
  test-fixtures/issues/issue-2231/cspell.yml
  test-fixtures/issues/issue-2231/sample.txt
Labels: fix

#2247 doc: RFC Proposal for Suggestion Lists
  lerna.json
  rfc/rfc-0001 suggestions/README.md
  rfc/rfc-0001 suggestions/jest.config.js
  rfc/rfc-0001 suggestions/package-lock.json
  rfc/rfc-0001 suggestions/package.json
  rfc/rfc-0001 suggestions/src/config-definitions.ts
  rfc/rfc-0001 suggestions/tsconfig.json
Labels: Documentation

#2250 doc: add comments about suggestions
  rfc/rfc-0001 suggestions/README.md
  rfc/rfc-0001 suggestions/src/config-definitions.ts
  rfc/rfc-0002 improve dictionary suggestions/README.md
Labels: Documentation

#2254 refactor: refactor cspell-trie-lib
  packages/cspell-trie-lib/package.json
  packages/cspell-trie-lib/src/lib/SimpleDictionaryParser.ts
  packages/cspell-trie-lib/src/lib/TrieBuilder.test.ts
  packages/cspell-trie-lib/src/lib/TrieBuilder.ts
  packages/cspell-trie-lib/src/lib/consolidate.test.ts
  packages/cspell-trie-lib/src/lib/consolidate.ts
  packages/cspell-trie-lib/src/lib/find.dutch.test.ts
  packages/cspell-trie-lib/src/lib/find.ts
  packages/cspell-trie-lib/src/lib/index.ts
  packages/cspell-trie-lib/src/lib/io/importExport.test.ts
  packages/cspell-trie-lib/src/lib/io/importExport.ts
  packages/cspell-trie-lib/src/lib/io/importExportV1.test.ts
  packages/cspell-trie-lib/src/lib/io/importExportV1.ts
  packages/cspell-trie-lib/src/lib/io/importExportV2.test.ts
  packages/cspell-trie-lib/src/lib/io/importExportV2.ts
  packages/cspell-trie-lib/src/lib/io/importExportV3.test.ts
  packages/cspell-trie-lib/src/lib/io/importExportV3.ts
  packages/cspell-trie-lib/src/lib/suggestions/orthography.test.ts
  packages/cspell-trie-lib/src/lib/suggestions/orthography.ts
  packages/cspell-trie-lib/src/lib/suggestions/suggest-en-a-star.test.ts
  packages/cspell-trie-lib/src/lib/suggestions/suggest-en.test.ts
  packages/cspell-trie-lib/src/lib/suggestions/suggest-es.test.ts
  packages/cspell-trie-lib/src/lib/suggestions/suggest-nl.test.ts
  packages/cspell-trie-lib/src/lib/suggestions/suggest.legacy.test.ts
  packages/cspell-trie-lib/src/lib/suggestions/suggest.test.ts
  packages/cspell-trie-lib/src/lib/suggestions/suggest.ts
  packages/cspell-trie-lib/src/lib/suggestions/suggestAStar.test.ts
  packages/cspell-trie-lib/src/lib/suggestions/suggestAStar.ts
  packages/cspell-trie-lib/src/lib/suggestions/suggestCollector.test.ts
  packages/cspell-trie-lib/src/lib/suggestions/suggestCollector.ts
  packages/cspell-trie-lib/src/lib/trie-util.test.ts
  packages/cspell-trie-lib/src/lib/trie-util.ts
  packages/cspell-trie-lib/src/lib/trie.en.test.ts
  packages/cspell-trie-lib/src/lib/trie.test.ts
  packages/cspell-trie-lib/src/lib/trie.ts
  packages/cspell-trie-lib/src/lib/utils/PairingHeap.test.ts
  packages/cspell-trie-lib/src/lib/utils/PairingHeap.ts
  packages/cspell-trie-lib/src/lib/utils/bufferLines.test.ts
  packages/cspell-trie-lib/src/lib/utils/bufferLines.ts
  packages/cspell-trie-lib/src/lib/utils/secondChanceCache.test.ts
  packages/cspell-trie-lib/src/lib/utils/secondChanceCache.ts
  packages/cspell-trie-lib/src/lib/utils/timer.test.ts
  packages/cspell-trie-lib/src/lib/utils/timer.ts
  packages/cspell-trie-lib/src/lib/walker.test.ts
  packages/cspell-trie-lib/src/lib/walker.ts
  packages/cspell-trie-lib/src/test/dictionaries.test.helper.ts
  packages/cspell-trie-lib/src/test/reader.test.helper.ts
  packages/cspell-trie-lib/src/test/samples.ts
  packages/cspell-trie2-lib/README.md
  packages/cspell-trie2-lib/package.json
Labels: fix

#2255 fix: Implement Weighted Distance Algorithm
  cspell-dict.txt
  packages/cspell-trie-lib/src/lib/suggestions/distanceAStar.test.ts
  packages/cspell-trie-lib/src/lib/suggestions/distanceAStar.ts
  packages/cspell-trie-lib/src/lib/suggestions/distanceAStarWeighted.test.ts
  packages/cspell-trie-lib/src/lib/suggestions/distanceAStarWeighted.ts
  packages/cspell-trie-lib/src/lib/suggestions/levenshtein.test.ts
  packages/cspell-trie-lib/src/lib/suggestions/levenshtein.ts
  packages/cspell-trie-lib/src/lib/suggestions/suggest.ts
  packages/cspell-trie-lib/src/lib/suggestions/weightedMaps.test.ts
  packages/cspell-trie-lib/src/lib/suggestions/weightedMaps.ts
  packages/cspell-trie-lib/src/lib/utils/PairingHeap.ts
  rfc/rfc-0002 improve dictionary suggestions/README.md
Labels: fix

#2256 refactor: turn on `exactOptionalPropertyTypes` in `cspell-trie-lib`
  packages/cspell-trie-lib/src/lib/TrieNode.ts
  packages/cspell-trie-lib/src/lib/find.ts
  packages/cspell-trie-lib/src/lib/flatten.ts
  packages/cspell-trie-lib/src/lib/index.ts
  packages/cspell-trie-lib/src/lib/io/importExportV2.ts
  packages/cspell-trie-lib/src/lib/suggest.ts
  packages/cspell-trie-lib/src/lib/suggestCollector.ts
  packages/cspell-trie-lib/src/lib/suggestions/suggest-en-a-star.test.ts
  packages/cspell-trie-lib/src/lib/suggestions/suggest-en.test.ts
  packages/cspell-trie-lib/src/lib/suggestions/suggest.ts
  packages/cspell-trie-lib/src/lib/suggestions/suggestAStar.test.ts
  packages/cspell-trie-lib/src/lib/suggestions/suggestCollector.ts
  packages/cspell-trie-lib/src/lib/trie-util.ts
  packages/cspell-trie-lib/src/lib/trie.test.ts
  packages/cspell-trie-lib/src/lib/trie.ts
  packages/cspell-trie-lib/src/lib/trieRef.ts
  packages/cspell-trie-lib/src/types.d.ts
  packages/cspell-trie-lib/tsconfig.json
Labels: fix

#2257 refactor: refactor distance calculations into their own folder
  packages/cspell-lib/src/SpellingDictionary/SpellingDictionaryFromTrie.ts
  packages/cspell-lib/src/index.ts
  packages/cspell-trie-lib/src/lib/distance/distance.test.ts
  packages/cspell-trie-lib/src/lib/distance/distance.ts
  packages/cspell-trie-lib/src/lib/distance/distanceAStar.test.ts
  packages/cspell-trie-lib/src/lib/distance/distanceAStar.ts
  packages/cspell-trie-lib/src/lib/distance/distanceAStarWeighted.test.ts
  packages/cspell-trie-lib/src/lib/distance/distanceAStarWeighted.ts
  packages/cspell-trie-lib/src/lib/distance/index.ts
  packages/cspell-trie-lib/src/lib/distance/levenshtein.test.ts
  packages/cspell-trie-lib/src/lib/distance/levenshtein.ts
  packages/cspell-trie-lib/src/lib/distance/weightedMaps.test.ts
  packages/cspell-trie-lib/src/lib/distance/weightedMaps.ts
  packages/cspell-trie-lib/src/lib/index.ts
Labels: fix

#2258 refactor: refactor type definitions for suggestion edit maps
  cspell.schema.json
  packages/cspell-trie-lib/src/__snapshots__/index.test.ts.snap
  packages/cspell-trie-lib/src/index.test.ts
  packages/cspell-trie-lib/src/lib/distance/distance.ts
  packages/cspell-trie-lib/src/lib/distance/index.ts
  packages/cspell-trie-lib/src/lib/distance/suggestionCostsDef.ts
  packages/cspell-trie-lib/src/lib/distance/weightedMaps.test.ts
  packages/cspell-trie-lib/src/lib/distance/weightedMaps.ts
  packages/cspell-trie-lib/src/lib/index.ts
  packages/cspell-types/cspell.schema.json
  packages/cspell-types/src/CSpellSettingsDef.ts
  packages/cspell-types/src/__snapshots__/index.test.ts.snap
  packages/cspell-types/src/index.test.ts
  packages/cspell-types/src/index.ts
  packages/cspell-types/src/suggestionCostsDef.ts
Labels: fix

#2268 refactor: Weighted distance calculations.
  packages/cspell-trie-lib/src/lib/distance/distance.test.ts
  packages/cspell-trie-lib/src/lib/distance/distance.ts
  packages/cspell-trie-lib/src/lib/distance/distanceAStarWeighted.test.ts
  packages/cspell-trie-lib/src/lib/distance/distanceAStarWeighted.ts
  packages/cspell-trie-lib/src/lib/distance/weightedMaps.test.ts
  packages/cspell-trie-lib/src/lib/distance/weightedMaps.ts
Labels: fix

#2277 fix: Lock in `typedoc` till it is fixed.
  packages/cspell-types/package-lock.json
  packages/cspell-types/package.json
Labels: Documentation, fix

#2280 ci: Move `test-build-docs` to speed up builds.
  .github/workflows/test-build-docs.yml
  package.json
  packages/cspell-types/package.json
Labels: Documentation, chore

#2286 fix: Handle missing files when spell checking from a file list.
  packages/cspell/src/fileHelper.test.ts
  packages/cspell/src/fileHelper.ts
  packages/cspell/src/lint/lint.test.ts
  packages/cspell/src/lint/lint.ts
  packages/cspell/src/options.ts
  packages/cspell/src/util/errors.test.ts
  packages/cspell/src/util/errors.ts
Labels: fix

#2287 refactor: to fix lint warning
  packages/cspell-trie-lib/src/lib/distance/weightedMaps.test.ts
Labels: fix

#2290 ci: forbid `therefor`
  cspell-dict.txt
  cspell.json
Labels: chore

#2291 fix: Add ability to discourage certain types of suggestions.
  cspell.schema.json
  packages/cspell-trie-lib/package-lock.json
  packages/cspell-trie-lib/package.json
  packages/cspell-trie-lib/src/lib/distance/distanceAStarWeighted.test.ts
  packages/cspell-trie-lib/src/lib/distance/distanceAStarWeighted.ts
  packages/cspell-trie-lib/src/lib/distance/suggestionCostsDef.ts
  packages/cspell-trie-lib/src/lib/distance/weightedMaps.test.ts
  packages/cspell-trie-lib/src/lib/distance/weightedMaps.ts
  packages/cspell-trie-lib/src/lib/suggestions/suggest-nl.test.ts
  packages/cspell-types/cspell.schema.json
  packages/cspell-types/src/suggestionCostsDef.ts
  rfc/rfc-0002 improve dictionary suggestions/README.md
Labels: fix

#2295 doc: Fix example typo and update support
  packages/cspell/README.md
Labels: Documentation, fix

#2296 fix: Move `suggestionEditCosts` into `dictionaryInformation`
  cspell.schema.json
  packages/cspell-types/cspell.schema.json
  packages/cspell-types/src/CSpellSettingsDef.ts
  packages/cspell-types/src/DictionaryInformation.ts
  packages/cspell-types/src/features.ts
Labels: fix

#2297 ci: Cache cspell results.
  .github/workflows/cspell-cli.yml
Labels: chore

#2298 ci: clean up cspell-cli workflow
  .github/workflows/cspell-cli.yml
Labels: chore

#2299 feat: Add cli command to show suggestions.
  packages/cspell-lib/src/Settings/DefaultSettings.ts
  packages/cspell-lib/src/Settings/index.ts
  packages/cspell-lib/src/__snapshots__/index.test.ts.snap
  packages/cspell-lib/src/index.test.ts
  packages/cspell-lib/src/index.ts
  packages/cspell-lib/src/suggestions.test.ts
  packages/cspell-lib/src/suggestions.ts
  packages/cspell-lib/src/trace.ts
  packages/cspell-lib/src/util/util.ts
  packages/cspell-trie-lib/src/lib/suggestions/suggestCollector.ts
  packages/cspell/src/__snapshots__/app.test.ts.snap
  packages/cspell/src/app.test.ts
  packages/cspell/src/app.ts
  packages/cspell/src/application.test.ts
  packages/cspell/src/application.ts
  packages/cspell/src/commandLink.ts
  packages/cspell/src/commandSuggestion.ts
  packages/cspell/src/commandTrace.ts
  packages/cspell/src/emitters/suggestionsEmitter.ts
  packages/cspell/src/emitters/traceEmitter.test.ts
  packages/cspell/src/emitters/traceEmitter.ts
  packages/cspell/src/lint/LintRequest.ts
  packages/cspell/src/options.test.ts
  packages/cspell/src/options.ts
  packages/cspell/src/util/errors.test.ts
  packages/cspell/src/util/stdin.test.ts
  packages/cspell/src/util/stdin.ts
  packages/cspell/src/util/util.test.ts
  packages/cspell/src/util/util.ts
Labels: feature

#2300 feat: Support using `stdin` for trace.
  packages/cspell-lib/src/__snapshots__/index.test.ts.snap
  packages/cspell-lib/src/index.ts
  packages/cspell-lib/src/trace.ts
  packages/cspell/src/__snapshots__/app.test.ts.snap
  packages/cspell/src/application.test.ts
  packages/cspell/src/application.ts
  packages/cspell/src/commandTrace.ts
  packages/cspell/src/options.ts
Labels: feature

#2303 ci: Update cspell-cli.yml
  .github/workflows/cspell-cli.yml
Labels: chore

#2302 fix: (cspell) Mark forbidden and no suggest words
  cspell-ignore-words.txt
  cspell.json
  packages/cspell-lib/src/Settings/CSpellSettingsServer.test.ts
  packages/cspell-lib/src/suggestions.ts
  packages/cspell-lib/src/trace.ts
  packages/cspell/src/__snapshots__/app.test.ts.snap
  packages/cspell/src/commandSuggestion.ts
  packages/cspell/src/emitters/__snapshots__/suggestionsEmitter.test.ts.snap
  packages/cspell/src/emitters/suggestionsEmitter.test.ts
  packages/cspell/src/emitters/suggestionsEmitter.ts
Labels: fix

#2306 docs: Add some more detail on getting started.
  docs/Gemfile.lock
  docs/docs/getting-started.md
  docs/docs/globs.md
  docs/docs/installation.md
  examples/cspell.config.yaml
  examples/cspell.json
Labels: Documentation

#2310 refactor: Clean up cspell-lib types
  packages/cspell-lib/api/api.d.ts
  packages/cspell-lib/api/rollup.config.mjs
  packages/cspell-lib/package-lock.json
  packages/cspell-lib/package.json
  packages/cspell-lib/src/Settings/CSpellSettingsInternalDef.ts
  packages/cspell-lib/src/Settings/CSpellSettingsServer.test.ts
  packages/cspell-lib/src/Settings/CSpellSettingsServer.ts
  packages/cspell-lib/src/Settings/DefaultSettings.ts
  packages/cspell-lib/src/Settings/DictionarySettings.ts
  packages/cspell-lib/src/Settings/index.link.ts
  packages/cspell-lib/src/SpellingDictionary/Dictionaries.test.ts
  packages/cspell-lib/src/SpellingDictionary/Dictionaries.ts
  packages/cspell-lib/src/__snapshots__/index.test.ts.snap
  packages/cspell-lib/src/index.ts
  packages/cspell-lib/src/suggestions.ts
  packages/cspell-lib/src/textValidator.test.ts
  packages/cspell-lib/src/trace.ts
  packages/cspell-lib/src/validator.ts
Labels: fix

#2313 ci: Add workflow to build docs from cspell-types
  .github/workflows/update-docs.yml
  package.json
Labels: Documentation, chore

#2315 fix: Make sure `${cwd}/` works in globs.
  packages/cspell-glob/src/__snapshots__/index.test.ts.snap
  packages/cspell-glob/src/globHelper.test.ts
  packages/cspell-glob/src/globHelper.ts
  packages/cspell-glob/src/index.test.ts
  packages/cspell-lib/api/api.d.ts
  packages/cspell-lib/src/Settings/CSpellSettingsServer.test.ts
  packages/cspell-lib/src/Settings/CSpellSettingsServer.ts
Labels: fix

#2316 fix: (cspell-glob) Make sure `cwd` can be set.
  packages/cspell-glob/src/GlobMatcher.test.ts
  packages/cspell-glob/src/GlobMatcher.ts
  packages/cspell-glob/src/globHelper.test.ts
Labels: fix

#2332 dev: Prepare to support Hunspell AFF to improve suggestions.
  cspell.schema.json
  packages/cspell-lib/api/api.d.ts
  packages/cspell-lib/src/Models/CSpellSettingsInternalDef.ts
  packages/cspell-lib/src/Settings/CSpellSettingsServer.test.ts
  packages/cspell-lib/src/Settings/CSpellSettingsServer.ts
  packages/cspell-lib/src/Settings/DefaultSettings.ts
  packages/cspell-lib/src/Settings/DictionarySettings.test.ts
  packages/cspell-lib/src/Settings/DictionarySettings.ts
  packages/cspell-lib/src/Settings/index.ts
  packages/cspell-lib/src/Settings/patterns.test.ts
  packages/cspell-lib/src/SpellingDictionary/Dictionaries.test.ts
  packages/cspell-lib/src/SpellingDictionary/Dictionaries.ts
  packages/cspell-lib/src/index.ts
  packages/cspell-lib/src/textValidator.test.ts
  packages/cspell-lib/src/trace.ts
  packages/cspell-trie-lib/src/lib/distance/__snapshots__/distanceAStarWeighted.test.ts.snap
  packages/cspell-trie-lib/src/lib/distance/distance.ts
  packages/cspell-trie-lib/src/lib/distance/distanceAStarWeighted.test.ts
  packages/cspell-trie-lib/src/lib/distance/distanceAStarWeighted.ts
  packages/cspell-trie-lib/src/lib/distance/index.ts
  packages/cspell-trie-lib/src/lib/distance/weightedMaps.test.ts
  packages/cspell-trie-lib/src/lib/distance/weightedMaps.ts
  packages/cspell-trie-lib/src/lib/index.ts
  packages/cspell-trie-lib/src/lib/mappers/__snapshots__/mapDictionaryInfoToWeightMap.test.ts.snap
  packages/cspell-trie-lib/src/lib/mappers/mapDictionaryInfoToWeightMap.test.ts
  packages/cspell-trie-lib/src/lib/mappers/mapDictionaryInfoToWeightMap.ts
  packages/cspell-trie-lib/src/lib/models/DictionaryInformation.ts
  packages/cspell-trie-lib/src/lib/models/suggestionCostsDef.ts
  packages/cspell-trie-lib/src/lib/utils/util.ts
  packages/cspell-types/cspell.schema.json
  packages/cspell-types/package.json
  packages/cspell-types/src/DictionaryInformation.ts
Labels: fix

#2307 feat: Add `failFast` config option to exit as soon as an issue encountered
  cspell.schema.json
  packages/cspell-lib/src/__snapshots__/index.test.ts.snap
  packages/cspell-types/cspell.schema.json
  packages/cspell-types/src/CSpellSettingsDef.ts
  packages/cspell-types/src/configFields.ts
  packages/cspell/samples/fail-fast/cspell.json
  packages/cspell/samples/fail-fast/fail-fast-cspell.json
  packages/cspell/samples/fail-fast/first-fail.txt
  packages/cspell/samples/fail-fast/second-fail.txt
  packages/cspell/src/lint/lint.test.ts
  packages/cspell/src/lint/lint.ts
Labels: feature

#2338 feat: add `--fail-fast` cli option
  cspell.schema.json
  packages/cspell-types/cspell.schema.json
  packages/cspell-types/src/CSpellSettingsDef.ts
  packages/cspell/src/__snapshots__/app.test.ts.snap
  packages/cspell/src/app.test.ts
  packages/cspell/src/commandLint.ts
  packages/cspell/src/lint/lint.test.ts
  packages/cspell/src/lint/lint.ts
  packages/cspell/src/options.ts
Labels: feature

#2340 fix: add `--fail-fast` to cspell README.md
  packages/cspell/README.md
Labels: fix

#2343 fix: Explicitly import `types`
  packages/cspell-trie-lib/src/lib/TrieNode.ts
  packages/cspell-trie-lib/src/lib/find.ts
  packages/cspell-trie-lib/src/lib/trie-util.ts
  packages/cspell-trie-lib/src/lib/types.ts
Labels: fix

#2342 feat: Support REPL style reading from stdin
  packages/cspell-gitignore/src/GitIgnore.ts
  packages/cspell/src/app.test.ts
  packages/cspell/src/application.test.ts
  packages/cspell/src/application.ts
  packages/cspell/src/lint/lint.ts
  packages/cspell/src/util/async.test.ts
  packages/cspell/src/util/async.ts
  packages/cspell/src/util/cache/CSpellLintResultCache.ts
  packages/cspell/src/util/cache/DiskCache.test.ts
  packages/cspell/src/util/cache/DiskCache.ts
  packages/cspell/src/util/cache/getConfigHash.ts
  packages/cspell/src/util/fileHelper.test.ts
  packages/cspell/src/util/fileHelper.ts
  packages/cspell/src/util/stdin.test.ts
  packages/cspell/src/util/util.test.ts
  packages/cspell/src/util/util.ts
Labels: feature

#2344 fix: Update tsconfig.json
  tsconfig.json
Labels: fix

#2346 fix: do not depend upon @types/glob in exports.
  packages/cspell/.gitignore
  packages/cspell/package-lock.json
  packages/cspell/package.json
  packages/cspell/rollup.config.mjs
  packages/cspell/src/app.ts
  packages/cspell/src/application.ts
  packages/cspell/src/util/glob.ts
Labels: fix

#2351 dev: Working towards weighted suggestions
  cspell.schema.json
  packages/cspell-lib/api/api.d.ts
  packages/cspell-lib/src/Models/CSpellSettingsInternalDef.ts
  packages/cspell-lib/src/Settings/DictionarySettings.ts
  packages/cspell-lib/src/SpellingDictionary/Dictionaries.test.ts
  packages/cspell-lib/src/SpellingDictionary/Dictionaries.ts
  packages/cspell-lib/src/SpellingDictionary/DictionaryLoader.test.ts
  packages/cspell-lib/src/SpellingDictionary/DictionaryLoader.ts
  packages/cspell-lib/src/SpellingDictionary/SpellingDictionary.test.ts
  packages/cspell-lib/src/SpellingDictionary/SpellingDictionary.ts
  packages/cspell-lib/src/SpellingDictionary/SpellingDictionaryCollection.test.ts
  packages/cspell-lib/src/SpellingDictionary/SpellingDictionaryCollection.ts
  packages/cspell-lib/src/SpellingDictionary/SpellingDictionaryFromTrie.ts
  packages/cspell-lib/src/SpellingDictionary/SpellingDictionaryMethods.ts
  packages/cspell-lib/src/SpellingDictionary/createSpellingDictionary.test.ts
  packages/cspell-lib/src/SpellingDictionary/createSpellingDictionary.ts
  packages/cspell-lib/src/textValidator.test.ts
  packages/cspell-lib/src/util/types.ts
  packages/cspell-trie-lib/package.json
  packages/cspell-trie-lib/src/__snapshots__/index.test.ts.snap
  packages/cspell-trie-lib/src/lib/distance/weightedMaps.ts
  packages/cspell-trie-lib/src/lib/index.ts
  packages/cspell-trie-lib/src/lib/mappers/__snapshots__/mapDictionaryInfoToWeightMap.test.ts.snap
  packages/cspell-trie-lib/src/lib/mappers/mapDictionaryInfoToWeightMap.test.ts
  packages/cspell-trie-lib/src/lib/mappers/mapDictionaryInfoToWeightMap.ts
  packages/cspell-trie-lib/src/lib/models/locale/index.ts
  packages/cspell-trie-lib/src/lib/models/locale/knownLocales.ts
  packages/cspell-trie-lib/src/lib/models/locale/locale.test.ts
  packages/cspell-trie-lib/src/lib/models/locale/locale.ts
  packages/cspell-trie-lib/src/lib/suggestions/suggest-nl.test.ts
  packages/cspell-trie-lib/src/lib/suggestions/suggest.test.ts
  packages/cspell-trie-lib/src/lib/utils/util.ts
  packages/cspell-trie-lib/src/test/dictionaries.test.helper.ts
  packages/cspell-types/cspell.schema.json
  packages/cspell-types/src/DictionaryInformation.ts
Labels: fix

#2357 fix: Show an error if a glob starts/ends with a single quote
  packages/cspell/src/lint/lint.test.ts
  packages/cspell/src/lint/lint.ts
Labels: fix

#2358 dev: Create cspell-pipe libarary
  packages/cspell-pipe/.gitignore
  packages/cspell-pipe/.vscode/launch.json
  packages/cspell-pipe/.vscode/tasks.json
  packages/cspell-pipe/CHANGELOG.md
  packages/cspell-pipe/LICENSE
  packages/cspell-pipe/README.md
  packages/cspell-pipe/jest.config.js
  packages/cspell-pipe/package-lock.json
  packages/cspell-pipe/package.json
  packages/cspell-pipe/src/__snapshots__/index.test.ts.snap
  packages/cspell-pipe/src/helpers/__snapshots__/index.test.ts.snap
  packages/cspell-pipe/src/helpers/index.test.ts
  packages/cspell-pipe/src/helpers/index.ts
  packages/cspell-pipe/src/helpers/toArray.ts
  packages/cspell-pipe/src/helpers/toAsyncIterable.ts
  packages/cspell-pipe/src/helpers/util.ts
  packages/cspell-pipe/src/index.test.ts
  packages/cspell-pipe/src/index.ts
  packages/cspell-pipe/src/internalTypes.ts
  packages/cspell-pipe/src/operators/__snapshots__/index.test.ts.snap
  packages/cspell-pipe/src/operators/await.test.ts
  packages/cspell-pipe/src/operators/await.ts
  packages/cspell-pipe/src/operators/filter.test.ts
  packages/cspell-pipe/src/operators/filter.ts
  packages/cspell-pipe/src/operators/flatten.test.ts
  packages/cspell-pipe/src/operators/flatten.ts
  packages/cspell-pipe/src/operators/index.test.ts
  packages/cspell-pipe/src/operators/index.ts
  packages/cspell-pipe/src/operators/joinStrings.test.ts
  packages/cspell-pipe/src/operators/joinStrings.ts
  packages/cspell-pipe/src/operators/map.test.ts
  packages/cspell-pipe/src/operators/map.ts
  packages/cspell-pipe/src/operators/unique.test.ts
  packages/cspell-pipe/src/operators/unique.ts
  packages/cspell-pipe/src/pipe.test.ts
  packages/cspell-pipe/src/pipe.ts
  packages/cspell-pipe/tsconfig.dev.json
  packages/cspell-pipe/tsconfig.json
Labels: fix

#2362 fix: Speed up spell checking with large config files.
  packages/cspell-lib/api/api.d.ts
  packages/cspell-lib/package-lock.json
  packages/cspell-lib/package.json
  packages/cspell-lib/src/Settings/CSpellSettingsServer.test.ts
  packages/cspell-lib/src/Settings/CSpellSettingsServer.ts
  packages/cspell-lib/src/Settings/DefaultSettings.ts
  packages/cspell-lib/src/Settings/InDocSettings.ts
  packages/cspell-lib/src/Settings/LanguageSettings.test.ts
  packages/cspell-lib/src/Settings/configLoader.test.ts
  packages/cspell-lib/src/Settings/configLoader.ts
  packages/cspell-lib/src/Settings/index.ts
  packages/cspell-lib/src/Settings/link.ts
  packages/cspell-lib/src/SpellingDictionary/Dictionaries.test.ts
  packages/cspell-lib/src/SpellingDictionary/Dictionaries.ts
  packages/cspell-lib/src/SpellingDictionary/createSpellingDictionary.ts
  packages/cspell-lib/src/util/simpleCache.test.ts
  packages/cspell-lib/src/util/simpleCache.ts
Labels: fix

#2363 fix: Speed up dictionaries from
  packages/cspell-lib/src/SpellingDictionary/Dictionaries.test.ts
  packages/cspell-lib/src/SpellingDictionary/Dictionaries.ts
  packages/cspell-lib/src/SpellingDictionary/DictionaryLoader.ts
Labels: fix

#2364 dev: move async to cspell-pipe
  cspell.code-workspace
  packages/cspell-pipe/package.json
  packages/cspell-pipe/src/__snapshots__/index.test.ts.snap
  packages/cspell-pipe/src/index.ts
  packages/cspell-pipe/src/operators/index.ts
  packages/cspell-trie-lib/package-lock.json
  packages/cspell-trie-lib/package.json
  packages/cspell-trie-lib/src/__snapshots__/index.test.ts.snap
  packages/cspell-trie-lib/src/index.ts
  packages/cspell-trie-lib/src/lib/mappers/mapDictionaryInfo.ts
  packages/cspell-trie-lib/src/lib/mappers/mapHunspellInformation.ts
  packages/cspell-trie-lib/src/lib/mappers/mapToSuggestionCostDef.ts
  packages/cspell-trie-lib/src/pipe/__snapshots__/index.test.ts.snap
  packages/cspell-trie-lib/src/pipe/helpers/__snapshots__/index.test.ts.snap
  packages/cspell-trie-lib/src/pipe/helpers/index.test.ts
  packages/cspell-trie-lib/src/pipe/helpers/index.ts
  packages/cspell-trie-lib/src/pipe/helpers/toArray.ts
  packages/cspell-trie-lib/src/pipe/helpers/toAsyncIterable.ts
  packages/cspell-trie-lib/src/pipe/helpers/util.ts
  packages/cspell-trie-lib/src/pipe/index.test.ts
  packages/cspell-trie-lib/src/pipe/index.ts
  packages/cspell-trie-lib/src/pipe/internalTypes.ts
  packages/cspell-trie-lib/src/pipe/operators/__snapshots__/index.test.ts.snap
  packages/cspell-trie-lib/src/pipe/operators/await.test.ts
  packages/cspell-trie-lib/src/pipe/operators/await.ts
  packages/cspell-trie-lib/src/pipe/operators/filter.test.ts
  packages/cspell-trie-lib/src/pipe/operators/filter.ts
  packages/cspell-trie-lib/src/pipe/operators/flatten.test.ts
  packages/cspell-trie-lib/src/pipe/operators/flatten.ts
  packages/cspell-trie-lib/src/pipe/operators/index.test.ts
  packages/cspell-trie-lib/src/pipe/operators/index.ts
  packages/cspell-trie-lib/src/pipe/operators/joinStrings.test.ts
  packages/cspell-trie-lib/src/pipe/operators/joinStrings.ts
  packages/cspell-trie-lib/src/pipe/operators/map.test.ts
  packages/cspell-trie-lib/src/pipe/operators/map.ts
  packages/cspell-trie-lib/src/pipe/operators/unique.test.ts
  packages/cspell-trie-lib/src/pipe/operators/unique.ts
  packages/cspell-trie-lib/src/pipe/pipe.test.ts
  packages/cspell-trie-lib/src/pipe/pipe.ts
  packages/cspell/package-lock.json
  packages/cspell/package.json
  packages/cspell/src/application.ts
  packages/cspell/src/lint/lint.ts
  packages/cspell/src/util/async.test.ts
  packages/cspell/src/util/async.ts
Labels: fix

#2367 fix: Upgrade to commander 9.0.0
  package.json
  packages/cspell/package-lock.json
  packages/cspell/package.json
  packages/cspell/src/__snapshots__/app.test.ts.snap
Labels: fix
