Repository streetsidesoftware/cspell, pull requests merged in 2024-05, with the labels that each got.

#5544 chore: prevent the summary from failing the build
  .github/workflows/integration-test.yml
Labels: chore

#5551 chore: Prettier, use single quote in Yaml files.
  .prettierrc.json
  cspell.code-workspace
  pnpm-workspace.yaml
Labels: chore

#5558 fix: Update schema generator
  packages/cspell-eslint-plugin/assets/options.schema.json
  packages/cspell-eslint-plugin/fixtures/cspell.config.yaml
  packages/cspell-eslint-plugin/package.json
  packages/cspell-eslint-plugin/src/test/index.test.mts
  packages/cspell-io/src/node/file/stat.test.ts
  packages/cspell-tools/package.json
  packages/cspell-types/src/DictionaryInformation.ts
  pnpm-lock.yaml
  scripts/build-cspell-schema.mjs
  scripts/package.json
Labels: fix

#5568 chore: Use force build
  packages/cspell-dictionary/package.json
  packages/cspell-eslint-plugin/package.json
  packages/cspell-gitignore/package.json
  packages/cspell-glob/package.json
  packages/cspell-grammar/package.json
  packages/cspell-io/package.json
  packages/cspell-json-reporter/package.json
  packages/cspell-lib/package.json
  packages/cspell-pipe/package.json
  packages/cspell-service-bus/package.json
  packages/cspell-strong-weak-map/package.json
  packages/cspell/package.json
  packages/dynamic-import/package.json
  test-packages/cspell-dictionary/test-cspell-dictionary/package.json
  test-packages/cspell-gitignore/test-cspell-gitignore/package.json
  test-packages/cspell-glob/test-cspell-glob/package.json
  test-packages/cspell-io/test-cspell-io/package.json
  test-packages/cspell-strong-weak-map/test-cspell-strong-weak-map/package.json
  test-packages/cspell-trie-lib/test-cspell-trie-lib/package.json
Labels: chore

#5569 fix: Drop dependency upon ConfigStore
  package.json
  packages/cspell-lib/package.json
  packages/cspell-lib/src/lib/Settings/GlobalSettings.test.ts
  packages/cspell-lib/src/lib/Settings/GlobalSettings.ts
  packages/cspell-lib/src/lib/Settings/cfgStore.test.ts
  packages/cspell-lib/src/lib/Settings/cfgStore.ts
  pnpm-lock.yaml
  test-packages/cspell-eslint-plugin/test-cspell-eslint-plugin-v8/package.json
  test-packages/cspell-eslint-plugin/test-cspell-eslint-plugin-v9/package.json
Labels: fix

#5584 fix: Add config field `enabledFileTypes `
  cspell.schema.json
  packages/cspell-lib/src/lib/Settings/CSpellSettingsServer.ts
  packages/cspell-lib/src/lib/__snapshots__/index.test.ts.snap
  packages/cspell-types/cspell.schema.json
  packages/cspell-types/src/CSpellSettingsDef.ts
  packages/cspell-types/src/configFields.ts
Labels: fix

#5588 chore: Remove deprecation message
  cspell.schema.json
  package.json
  packages/cspell-types/cspell.schema.json
  packages/cspell-types/src/CSpellSettingsDef.ts
  scripts/jsconfig.json
  scripts/package.json
  scripts/remove-zero-width-space.mjs
Labels: chore

#5590 chore: Update dependencies
  package.json
  packages/cspell-eslint-plugin/package.json
  packages/cspell-eslint-plugin/src/plugin/cspell-eslint-plugin.cts
  packages/cspell-io/src/node/file/_fetch.ts
  packages/cspell-io/src/node/file/fetch.test.ts
  packages/cspell-io/src/node/file/fetch.ts
  packages/cspell-tools/package.json
  packages/cspell/package.json
  pnpm-lock.yaml
  scripts/package.json
  test-packages/cspell-eslint-plugin/test-cspell-eslint-plugin-v8/package.json
  test-packages/cspell-eslint-plugin/test-cspell-eslint-plugin-v9/package.json
  test-packages/cspell-lib/test-cspell-esbuild-cjs/source/package.json
  test-packages/cspell/test-cspell-esbuild-cjs/source/package.json
  tools/perf-chart/lib/app.cjs
  tools/perf-chart/package.json
Labels: chore

#5595 docs: New Docusaurus Site
  pnpm-lock.yaml
  website/README.md
  website/babel.config.js
  website/blog/2019-05-28-first-blog-post.md
  website/blog/2019-05-29-long-blog-post.md
  website/blog/2021-08-01-mdx-blog-post.mdx
  website/blog/2021-08-26-welcome/docusaurus-plushie-banner.jpeg
  website/blog/2021-08-26-welcome/index.md
  website/blog/authors.yml
  website/docs/Configuration/document-settings.md
  website/docs/Configuration/imports.md
  website/docs/Configuration/index.md
  website/docs/Configuration/language-settings.md
  website/docs/Configuration/overrides.md
  website/docs/Configuration/patterns.md
  website/docs/case-sensitive.md
  website/docs/command-check.md
  website/docs/command-trace.md
  website/docs/dictionaries-custom.md
  website/docs/dictionaries.md
  website/docs/forbidden-words.md
  website/docs/getting-started.md
  website/docs/git.md
  website/docs/globs.md
  website/docs/how-it-works.md
  website/docs/installation.md
  website/docs/intro.md
  website/docs/tutorial-basics/_category_.json
  website/docs/tutorial-basics/congratulations.md
  website/docs/tutorial-basics/create-a-blog-post.md
  website/docs/tutorial-basics/create-a-document.md
  website/docs/tutorial-basics/create-a-page.md
  website/docs/tutorial-basics/deploy-your-site.md
  website/docs/tutorial-basics/markdown-features.mdx
  website/docs/tutorial-extras/_category_.json
  website/docs/tutorial-extras/img/docsVersionDropdown.png
  website/docs/tutorial-extras/img/localeDropdown.png
  website/docs/tutorial-extras/manage-docs-versions.md
  website/docs/tutorial-extras/translate-your-site.md
  website/docusaurus.config.ts
  website/package.json
  website/sidebars.ts
  website/src/components/HomepageFeatures/index.tsx
  website/src/components/HomepageFeatures/styles.module.css
  website/src/css/custom.css
  website/src/pages/about.md
  website/src/pages/assets/paypal-logo-wide-16.png
  website/src/pages/assets/paypal.png
  website/src/pages/assets/paypal.svg
  website/src/pages/index.module.css
  website/src/pages/index.tsx
  website/static/img/docusaurus-social-card.jpg
  website/static/img/docusaurus.png
  website/static/img/favicon.ico
  website/static/img/logo.png
  website/static/img/logo.svg
Labels: Documentation

#5597 docs: fix website deploy
  .github/workflows/deploy-website.yml
  website/docusaurus.config.ts
  website/package.json
Labels: Documentation

#5598 docs: fix links
  .github/workflows/website-lint.yml
  docs/configuration/index.md
  website/docs/Configuration/index.md
  website/docs/Configuration/language-settings.mdx
  website/docs/dictionaries.md
  website/package.json
Labels: Documentation

#5599 docs: Generate API Documentation
  .github/workflows/deploy-website.yml
  .github/workflows/website-test.yml
  doc-generator/package.json
  packages/cspell-lib/README.md
  packages/cspell-types/README.md
  pnpm-lock.yaml
  static/footer.md
  website/.gitignore
  website/docusaurus.config.ts
  website/package.json
Labels: Documentation

#5600 docs: Navbar structure
  website/docs/Configuration/index.md
  website/docs/configuration/_category_.yaml
  website/docs/dictionaries/_category_.yaml
  website/docs/dictionaries/custom-dictionaries.md
  website/docs/dictionaries/index.md
  website/docs/dictionaries/searching-dictionaries.md
  website/docs/getting-started.md
  website/docs/how-it-works.md
  website/docs/installation.md
  website/src/css/custom.css
Labels: Documentation

#5607 docs: Add more pages and clean up
  packages/cspell/README.md
  pnpm-lock.yaml
  website/README.md
  website/docs/getting-started.mdx
  website/docs/installation.md
  website/docusaurus.config.ts
  website/package.json
  website/src/css/custom.css
Labels: Documentation

#5630 chore: extend the integration report for Django
  integration-tests/config/config.json
  integration-tests/snapshots/django/django/report.yaml
  integration-tests/snapshots/django/django/snapshot.txt
Labels: chore

#5644 chore: fix footer
  static/footer.md
Labels: chore

#5648 fix: lock version of `micromatch`
  packages/cspell-glob/package.json
  pnpm-lock.yaml
Labels: fix

#5650 chore: verify that micromatch update does not break CSpell.
  packages/cspell-glob/package.json
  packages/cspell-glob/src/GlobMatcher.test.ts
  packages/cspell/package.json
  packages/cspell/src/app/util/glob.test.ts
  pnpm-lock.yaml
Labels: chore

#5666 fix: bundle the Google Cloud dictionary
  .github/workflows/update-dependencies.yml
  package.json
  packages/cspell-bundled-dicts/cspell-default.config.js
  packages/cspell-bundled-dicts/cspell-default.config.ts
  packages/cspell-bundled-dicts/package.json
  packages/cspell/src/app/__snapshots__/app.test.ts.snap
  pnpm-lock.yaml
Labels: fix
