Repository streetsidesoftware/cspell, pull requests merged in 2024-09, with the labels that each got.

#6223 chore: lock TypeScript version
  package.json
  packages/cspell-eslint-plugin/package.json
  packages/cspell-io/package.json
  pnpm-lock.yaml
  website/package.json
Labels: chore

#6225 chore: update packages
  doc-generator/package.json
  package.json
  packages/cspell-eslint-plugin/package.json
  packages/cspell-eslint-plugin/src/test/import.test.mts
  packages/cspell-eslint-plugin/src/test/index.test.mts
  packages/cspell-eslint-plugin/src/test/json.test.mts
  packages/cspell-eslint-plugin/src/test/jsx.test.mts
  packages/cspell-eslint-plugin/src/test/yaml.test.mts
  pnpm-lock.yaml
  test-packages/cspell-eslint-plugin/test-cspell-eslint-plugin-v9-basic/package.json
  test-packages/cspell-eslint-plugin/test-cspell-eslint-plugin-v9/package.json
  website/package.json
Labels: chore

#6229 chore: Add example of dynamic config
  examples/dynamic-dictionaries/README.md
  examples/dynamic-dictionaries/cspell.config.cjs
  examples/dynamic-dictionaries/cspell.config.mjs
  examples/dynamic-dictionaries/dictionaries/a.txt
  examples/dynamic-dictionaries/dictionaries/b.txt
  examples/dynamic-dictionaries/dictionaries/c.txt
  examples/dynamic-dictionaries/dictionaries/t.txt
  examples/dynamic-dictionaries/package.json
  packages/Samples/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: chore

#6231 docs: minor tweaks
  website/cspell.config.yaml
  website/docusaurus.config.ts
  website/src/pages/index.md
  website/src/pages/index.tsx
  website/src/pages/markdown-page.md
Labels: Documentation

#6234 docs: build docs
  website/_scripts/extract-properties.mjs
  website/_scripts/lib/utils.mjs
  website/docs/Configuration/auto_properties.md
Labels: Documentation

#6243 fix: Make flatpack-json diff friendly.
  cspell-dict.txt
  packages/flatpack-json/package.json
  packages/flatpack-json/scripts/flatten.mjs
  packages/flatpack-json/src/Flatpack.mts
  packages/flatpack-json/src/Flatpack.test.mts
  packages/flatpack-json/src/RefElements.mts
  packages/flatpack-json/src/Trie.mts
  packages/flatpack-json/src/__snapshots__/Flatpack.test.mts.snap
  packages/flatpack-json/src/__snapshots__/Flatpack_fileList.data.json
  packages/flatpack-json/src/__snapshots__/Flatpack_fileList.json
  packages/flatpack-json/src/__snapshots__/Flatpack_fileList.jsonc
  packages/flatpack-json/src/__snapshots__/Flatpack_fileObjects.data.json
  packages/flatpack-json/src/__snapshots__/Flatpack_fileObjects.json
  packages/flatpack-json/src/__snapshots__/Flatpack_fileObjects.jsonc
  packages/flatpack-json/src/__snapshots__/fileList.jsonc
  packages/flatpack-json/src/__snapshots__/fileObjects.jsonc
  packages/flatpack-json/src/__snapshots__/storage.test.mts.snap
  packages/flatpack-json/src/__snapshots__/storage_fileList.data.json
  packages/flatpack-json/src/__snapshots__/storage_fileList.json
  packages/flatpack-json/src/__snapshots__/storage_fileList.jsonc
  packages/flatpack-json/src/__snapshots__/storage_fileObjects.data.json
  packages/flatpack-json/src/__snapshots__/storage_fileObjects.json
  packages/flatpack-json/src/__snapshots__/storage_fileObjects.jsonc
  packages/flatpack-json/src/__snapshots__/unpack.test.mts.snap
  packages/flatpack-json/src/__snapshots__/unpack_fileList.data.json
  packages/flatpack-json/src/__snapshots__/unpack_fileList.json
  packages/flatpack-json/src/__snapshots__/unpack_fileList.jsonc
  packages/flatpack-json/src/__snapshots__/unpack_fileObjects.data.json
  packages/flatpack-json/src/__snapshots__/unpack_fileObjects.json
  packages/flatpack-json/src/__snapshots__/unpack_fileObjects.jsonc
  packages/flatpack-json/src/index.ts
  packages/flatpack-json/src/storage.mts
  packages/flatpack-json/src/storage.test.mts
  packages/flatpack-json/src/stringify.mts
  packages/flatpack-json/src/types.mts
  packages/flatpack-json/src/unpack.mts
  packages/flatpack-json/src/unpack.test.mts
  pnpm-lock.yaml
Labels: fix

#6252 fix: Add ability to unpack and preserve order
  packages/flatpack-json/src/Flatpack.mts
  packages/flatpack-json/src/Flatpack.test.mts
  packages/flatpack-json/src/RefElements.mts
  packages/flatpack-json/src/flatpackUtil.mts
  packages/flatpack-json/src/types.mts
  packages/flatpack-json/src/unpack.mts
Labels: fix

#6257 fix: Remove object from cache
  packages/flatpack-json/src/Flatpack.mts
  packages/flatpack-json/src/Flatpack.test.mts
Labels: fix

#6264 refactor: works towards dynamic flatpack
  packages/flatpack-json/src/Flatpack.mts
  packages/flatpack-json/src/Flatpack.test.mts
  packages/flatpack-json/src/RefElements.mts
  packages/flatpack-json/src/proxy.mts
  packages/flatpack-json/src/proxy.test.mts
Labels: fix

#6265 chore: Add example
  examples/invoke-cspell/README.md
  examples/invoke-cspell/cspell.config.yaml
  examples/invoke-cspell/index.mjs
  examples/invoke-cspell/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: chore

#6270 chore: Update `@types/estree`
  packages/cspell-eslint-plugin/package.json
  packages/cspell-eslint-plugin/src/worker/spellCheck.mts
  pnpm-lock.yaml
Labels: chore
