Repository streetsidesoftware/cspell, pull requests merged in 2024-06, with the labels that each got.

#5698 fix: improve URL detection
  packages/cspell-io/src/node/file/url.test.ts
  packages/cspell-io/src/node/file/url.ts
  packages/cspell-lib/src/lib/util/Uri.test.ts
  packages/cspell-lib/src/lib/util/Uri.ts
Labels: fix

#5709 chore: update docusaurus
  pnpm-lock.yaml
  website/package.json
Labels: chore

#5723 docs: generate docs
  website/_scripts/extract-properties.mjs
  website/cspell.config.yaml
  website/docs/Configuration/auto_properties.md
  website/package.json
Labels: Documentation

#5729 fix: Workflow Bot -- Update Dictionaries
  integration-tests/repositories/cspell.yaml
  integration-tests/snapshots/microsoft/TypeScript-Website/report.yaml
  integration-tests/snapshots/microsoft/TypeScript-Website/snapshot.txt
  integration-tests/snapshots/neovim/nvim-lspconfig/report.yaml
  integration-tests/snapshots/neovim/nvim-lspconfig/snapshot.txt
  integration-tests/snapshots/sveltejs/svelte/report.yaml
  integration-tests/snapshots/sveltejs/svelte/snapshot.txt
  packages/cspell-bundled-dicts/package.json
  pnpm-lock.yaml
Labels: fix

#5739 docs: work on configuration page
  website/_scripts/extract-properties.mjs
  website/docs/Configuration/auto_properties.md
Labels: Documentation

#5741 feat: Support spell checking more document types
  packages/cspell-eslint-plugin/README.md
  packages/cspell-eslint-plugin/assets/options.schema.json
  packages/cspell-eslint-plugin/fixtures/json-support/README.md
  packages/cspell-eslint-plugin/fixtures/json-support/eslint.config.mjs
  packages/cspell-eslint-plugin/fixtures/json-support/package.json
  packages/cspell-eslint-plugin/fixtures/json-support/sample.jsonc
  packages/cspell-eslint-plugin/fixtures/mdx-support/README.md
  packages/cspell-eslint-plugin/fixtures/mdx-support/eslint.config.mjs
  packages/cspell-eslint-plugin/fixtures/mdx-support/md-with-code.mdx
  packages/cspell-eslint-plugin/fixtures/mdx-support/package.json
  packages/cspell-eslint-plugin/fixtures/yaml-support/eslint.config.mjs
  packages/cspell-eslint-plugin/fixtures/yaml-support/sample.yaml
  packages/cspell-eslint-plugin/package.json
  packages/cspell-eslint-plugin/src/common/options.cts
  packages/cspell-eslint-plugin/src/plugin/cspell-eslint-plugin.cts
  packages/cspell-eslint-plugin/src/plugin/defaultCheckOptions.cts
  packages/cspell-eslint-plugin/src/test-util/testEach.mts
  packages/cspell-eslint-plugin/src/test-util/tsconfig.json
  packages/cspell-eslint-plugin/src/test/index.test.mts
  packages/cspell-eslint-plugin/src/test/json.test.mts
  packages/cspell-eslint-plugin/src/test/jsx.test.mts
  packages/cspell-eslint-plugin/src/test/yaml.test.mts
  packages/cspell-eslint-plugin/src/worker/ASTNode.cts
  packages/cspell-eslint-plugin/src/worker/ASTPath.mts
  packages/cspell-eslint-plugin/src/worker/customScopes.mts
  packages/cspell-eslint-plugin/src/worker/scope.mts
  packages/cspell-eslint-plugin/src/worker/scope.test.mts
  packages/cspell-eslint-plugin/src/worker/spellCheck.mts
  packages/cspell-eslint-plugin/src/worker/tsconfig.json
  packages/cspell-eslint-plugin/src/worker/walkTree.mts
  pnpm-lock.yaml
  website/docs/Configuration/auto_properties.md
Labels: feature

#5742 docs: change `<dl>` indent in generated markdown
  website/_scripts/extract-properties.mjs
  website/docs/Configuration/_category_.yaml
  website/docs/Configuration/auto_properties.md
Labels: Documentation

#5749 chore: Do not format auto generated content
  website/.prettierignore
Labels: chore

#5750 chore: Update .prettierignore
  .prettierignore
Labels: chore

#5754 docs: Use `inject` template function
  website/_scripts/extract-properties.mjs
Labels: Documentation

#5780 fix: Make sure binary files are not checked.
  packages/cspell-lib/api/api.d.ts
  packages/cspell-lib/src/lib/Document/isBinaryDoc.test.ts
  packages/cspell-lib/src/lib/Document/isBinaryDoc.ts
  packages/cspell-lib/src/lib/LanguageIds.ts
  packages/cspell-lib/src/lib/spellCheckFile.test.ts
  packages/cspell-lib/src/lib/spellCheckFile.ts
Labels: fix

#5776 docs: format tables in generated docs
  website/_scripts/extract-properties.mjs
  website/_scripts/jsconfig.json
  website/docs/Configuration/auto_properties.md
Labels: Documentation

#5792 chore: Update to TypeScript 5.5.2
  package.json
  packages/cspell-lib/api/api.d.ts
  packages/cspell-lib/src/lib/Settings/RegExpPatterns.ts
  packages/cspell-trie-lib/api/api.d.ts
  pnpm-lock.yaml
Labels: chore

#5796 chore: Upgrade Pnpm to v9
  package.json
  pnpm-lock.yaml
Labels: chore

#5790 fix: resolve imports from ESLint plugin
  packages/cspell-eslint-plugin/README.md
  packages/cspell-eslint-plugin/assets/options.schema.json
  packages/cspell-eslint-plugin/cspell.config.yaml
  packages/cspell-eslint-plugin/fixtures/import-support/cspell.config.yaml
  packages/cspell-eslint-plugin/fixtures/import-support/cspell.test.json
  packages/cspell-eslint-plugin/fixtures/import-support/sample.ts
  packages/cspell-eslint-plugin/package.json
  packages/cspell-eslint-plugin/src/common/options.cts
  packages/cspell-eslint-plugin/src/plugin/cspell-eslint-plugin.cts
  packages/cspell-eslint-plugin/src/plugin/defaultCheckOptions.cts
  packages/cspell-eslint-plugin/src/test/import.test.mts
  packages/cspell-eslint-plugin/src/worker/spellCheck.mts
  packages/cspell-lib/api/api.d.ts
  packages/cspell-lib/src/lib/Settings/Controller/configLoader/configLoader.ts
  packages/cspell-lib/src/lib/Settings/Controller/configLoader/defaultConfigLoader.ts
  packages/cspell-lib/src/lib/Settings/Controller/configLoader/index.ts
  packages/cspell-lib/src/lib/Settings/index.ts
  packages/cspell-lib/src/lib/textValidation/docValidator.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
  test-fixtures/dictionaries/test-dictionary/index.js
  test-fixtures/dictionaries/test-dictionary/package.json
  test-fixtures/dictionaries/test-dictionary/words.txt
Labels: fix

#5805 test: Start measuring trie has perf
  packages/cspell-trie-lib/package.json
  packages/cspell-trie-lib/src/perf/has.perf.ts
Labels: test

#5806 fix: Make sure case sensitive trace works as expected.
  .gitattributes
  packages/cspell-lib/api/api.d.ts
  packages/cspell-lib/src/lib/textValidation/traceWord.ts
  packages/cspell-lib/src/lib/trace.test.ts
  packages/cspell-lib/src/lib/trace.ts
  packages/cspell/src/app/__snapshots__/app.test.ts.snap
  packages/cspell/src/app/commandTrace.ts
  packages/cspell/src/app/emitters/suggestionsEmitter.ts
  packages/cspell/src/app/emitters/traceEmitter.test.ts
  packages/cspell/src/app/emitters/traceEmitter.ts
  packages/cspell/src/app/util/pad.test.ts
  packages/cspell/src/app/util/pad.ts
  packages/cspell/src/app/util/table.ts
  packages/cspell/src/app/util/util.test.ts
  packages/cspell/src/app/util/util.ts
Labels: fix

#5807 docs: Remove references to OpenBase
  README.md
  docs/_includes/generated-docs/README.md
Labels: Documentation

#5826 fix: Always set the color to white
  packages/cspell/src/app/cli-reporter.ts
Labels: fix

#5824 feat: Add glob support for URLs
  .prettierrc.json
  cspell.code-workspace
  packages/cspell-gitignore/package.json
  packages/cspell-gitignore/src/GitIgnore.test.ts
  packages/cspell-gitignore/src/GitIgnoreFile.test.ts
  packages/cspell-gitignore/src/__snapshots__/app.test.ts.snap
  packages/cspell-gitignore/src/app.test.ts
  packages/cspell-gitignore/src/app.ts
  packages/cspell-gitignore/tsconfig.esm.json
  packages/cspell-gitignore/tsconfig.json
  packages/cspell-glob/package.json
  packages/cspell-glob/src/GlobMatcher.test.ts
  packages/cspell-glob/src/GlobMatcher.ts
  packages/cspell-glob/src/GlobMatcherTypes.ts
  packages/cspell-glob/src/globHelper.test.ts
  packages/cspell-glob/src/globHelper.ts
  packages/cspell-glob/src/perf/match.perf.ts
  packages/cspell-glob/tsconfig.esm.json
  packages/cspell-glob/tsconfig.json
  packages/cspell-io/src/CSpellIONode.test.ts
  packages/cspell-io/src/CVirtualFS.ts
  packages/cspell-io/src/VFileSystem.ts
  packages/cspell-io/src/VirtualFS.ts
  packages/cspell-io/src/VirtualFS/CVFileSystem.test.ts
  packages/cspell-io/src/VirtualFS/CVFileSystem.ts
  packages/cspell-io/src/VirtualFS/WrappedProviderFs.ts
  packages/cspell-io/src/VirtualFS/findUpFromUrl.test.ts
  packages/cspell-io/src/VirtualFS/findUpFromUrl.ts
  packages/cspell-io/src/VirtualFS/redirectProvider.test.ts
  packages/cspell-io/src/VirtualFS/redirectProvider.ts
  packages/cspell-io/src/VirtualFs.test.ts
  packages/cspell-io/src/index.ts
  packages/cspell-io/src/models/LogEvent.ts
  packages/cspell-url/package.json
  packages/cspell-url/src/FileUrlBuilder.mts
  packages/cspell-url/src/FileUrlBuilder.test.mts
  packages/cspell-url/src/defaultFileUrlBuilder.mts
  packages/cspell-url/src/fileUrl.mts
  packages/cspell-url/src/fileUrl.test.mts
  packages/cspell-url/src/index.mts
  packages/cspell-url/src/perf/url.perf.ts
  packages/cspell-url/src/url.mts
  packages/cspell-url/src/url.test.mts
  packages/cspell/fixtures/globRoot/config/cspell.config.yaml
  packages/cspell/fixtures/globRoot/cspell.json
  packages/cspell/fixtures/globRoot/src/ignore-me.md
  packages/cspell/src/app/__snapshots__/app.test.ts.snap
  packages/cspell/src/app/app.test.ts
  pnpm-lock.yaml
  test-fixtures/perf/cspell-glob/data/file-list.txt
  test-fixtures/perf/cspell-glob/data/patterns.jsonc
  test-packages/cspell-glob/test-cspell-glob/bin.mjs
  test-packages/cspell-glob/test-cspell-glob/bin.rollup.cjs
  test-packages/cspell-glob/test-cspell-glob/bin.rollup.mjs
  test-packages/cspell-glob/test-cspell-glob/src/index.test.ts
Labels: feature

#5834 chore: Remove duplicate findUp
  packages/cspell-io/src/index.ts
  packages/cspell-lib/src/lib/util/findUpFromUrl.ts
Labels: chore
