Repository streetsidesoftware/cspell, pull requests merged in 2025-04, with the labels that each got.

#7113 chore: Do not run prettier on `.mdx` files.
  .prettierignore
Labels: chore

#7152 test: Update integration
  integration-tests/config/config.json
  integration-tests/snapshots/webdeveric/webpack-assets-manifest/report.yaml
  integration-tests/snapshots/webdeveric/webpack-assets-manifest/snapshot.txt
Labels: test

#7175 chore: update lerna-lite
  package.json
  pnpm-lock.yaml
Labels: chore

#7182 feat: Be able to ignore forbidden words in a dictionary
  cspell.schema.json
  packages/cspell-dictionary/src/SpellingDictionary/SpellingDictionary.test.ts
  packages/cspell-dictionary/src/SpellingDictionary/SpellingDictionary.ts
  packages/cspell-dictionary/src/SpellingDictionary/SpellingDictionaryCollection.test.ts
  packages/cspell-dictionary/src/SpellingDictionary/SpellingDictionaryCollection.ts
  packages/cspell-dictionary/src/SpellingDictionary/SpellingDictionaryFromTrie.ts
  packages/cspell-dictionary/src/SpellingDictionary/SuggestOptions.ts
  packages/cspell-eslint-plugin/src/generated/schema.cts
  packages/cspell-lib/samples/ignore-forbidden-dutch-words/README.md
  packages/cspell-lib/samples/ignore-forbidden-dutch-words/cspell.config.mjs
  packages/cspell-lib/src/lib/Settings/DictionarySettings.ts
  packages/cspell-lib/src/lib/test/dutch.spec.ts
  packages/cspell-lib/src/lib/test/dutch2.spec.ts
  packages/cspell-trie-lib/api/api.d.ts
  packages/cspell-trie-lib/src/lib/ITrie.ts
  packages/cspell-trie-lib/src/lib/ITrieNode/find.test.ts
  packages/cspell-trie-lib/src/lib/ITrieNode/find.ts
  packages/cspell-trie-lib/src/lib/ITrieNode/index.ts
  packages/cspell-trie-lib/src/lib/index.ts
  packages/cspell-trie-lib/src/lib/suggestions/genSuggestionsOptions.ts
  packages/cspell-trie-lib/src/lib/suggestions/suggest.ts
  packages/cspell-trie-lib/src/lib/suggestions/suggestAStar.ts
  packages/cspell-trie-lib/src/lib/suggestions/suggestCollector.ts
  packages/cspell-trie-lib/src/lib/trie.ts
  packages/cspell-types/cspell.schema.json
  packages/cspell-types/src/DictionaryDefinition.ts
Labels: feature

#7195 fix: Workaround picomatch bug
  packages/cspell-glob/package.json
  packages/cspell-glob/src/GlobMatcher.test.ts
  packages/cspell-glob/src/GlobMatcher.ts
  packages/cspell-glob/src/__snapshots__/index.test.ts.snap
  packages/cspell-glob/src/globHelper.ts
  packages/cspell-glob/src/index.ts
  packages/cspell/src/app/util/glob.test.ts
  packages/cspell/src/app/util/glob.ts
  pnpm-lock.yaml
Labels: fix

#7199 fix: improve eslint plugin perf
  eslint.config.mjs
  packages/cspell-eslint-plugin/eslint.config.js
  packages/cspell-eslint-plugin/package.json
  packages/cspell-eslint-plugin/scripts/build-options-schema.mjs
  packages/cspell-eslint-plugin/src/generated/schema.cts
  packages/cspell-eslint-plugin/src/plugin/cspell-eslint-plugin.cts
  packages/cspell-eslint-plugin/src/plugin/tsconfig.json
  packages/cspell-eslint-plugin/src/spellCheckAST/ASTNode.ts
  packages/cspell-eslint-plugin/src/spellCheckAST/ASTPath.ts
  packages/cspell-eslint-plugin/src/spellCheckAST/customScopes.cts
  packages/cspell-eslint-plugin/src/spellCheckAST/index.cts
  packages/cspell-eslint-plugin/src/spellCheckAST/scope.cts
  packages/cspell-eslint-plugin/src/spellCheckAST/scope.test.mts
  packages/cspell-eslint-plugin/src/spellCheckAST/spellCheck.mts
  packages/cspell-eslint-plugin/src/spellCheckAST/spellCheck.test.mts
  packages/cspell-eslint-plugin/src/spellCheckAST/spellCheckAST.cts
  packages/cspell-eslint-plugin/src/spellCheckAST/tsconfig.json
  packages/cspell-eslint-plugin/src/spellCheckAST/types.ts
  packages/cspell-eslint-plugin/src/spellCheckAST/walkTree.cts
  packages/cspell-eslint-plugin/src/spellCheckAST/worker.mts
  packages/cspell-eslint-plugin/src/synckit/index.cts
  packages/cspell-eslint-plugin/src/synckit/tsconfig.json
  packages/cspell-eslint-plugin/src/test/tsconfig.json
  packages/cspell-eslint-plugin/src/worker/tsconfig.json
  packages/cspell-eslint-plugin/src/worker/worker.mts
  packages/cspell-eslint-plugin/tsconfig.json
  packages/cspell-lib/api/api.d.ts
  packages/cspell-lib/src/lib/textValidation/docValidator.ts
Labels: fix

#7211 chore: Update vitest
  package.json
  packages/dynamic-import/src/esm/index.test.mts
  packages/dynamic-import/src/test/index.test.ts
  pnpm-lock.yaml
Labels: chore

#7219 test: fix `twbs/bootstrap` integration test
  integration-tests/config/config.json
  integration-tests/snapshots/twbs/bootstrap/report.yaml
  integration-tests/snapshots/twbs/bootstrap/snapshot.txt
Labels: test

#7229 fix: Replace `get-stdin` with native alternative
  packages/cspell/package.json
  packages/cspell/src/app/application.test.ts
  packages/cspell/src/app/util/fileHelper.test.ts
  packages/cspell/src/app/util/fileHelper.ts
  packages/cspell/src/app/util/glob.test.ts
  pnpm-lock.yaml
Labels: fix

#7234 feat: resolve config from global path
  packages/cspell/samples/environment_config/cspell.custom.json
  packages/cspell/samples/environment_config/cspell.default.json
  packages/cspell/samples/environment_config/sample.tex
  packages/cspell/samples/environment_config/sample.txt
  packages/cspell/src/app/environment.ts
  packages/cspell/src/app/lint/lint.test.ts
  packages/cspell/src/app/util/fileHelper.ts
Labels: fix

#7240 fix: Adjust the meaning of CSPELL_DEFAULT_CONFIG_PATH
  packages/cspell/samples/environment_config/cspell.custom.json
  packages/cspell/samples/environment_config/cspell.default.json
  packages/cspell/samples/environment_config/cspell.yaml
  packages/cspell/src/app/application.mts
  packages/cspell/src/app/lint/lint.test.ts
  packages/cspell/src/app/lint/lint.ts
  packages/cspell/src/app/util/configFileHelper.test.ts
  packages/cspell/src/app/util/configFileHelper.ts
  packages/cspell/src/app/util/fileHelper.ts
Labels: fix

#7248 fix: Reduce the flatpack JSON size
  cspell.code-workspace
  packages/cspell-normalize-json/src/__snapshots__/fileList.json
  packages/cspell-normalize-json/src/__snapshots__/fileList.jsonc
  packages/cspell-normalize-json/src/__snapshots__/fileObjects.json
  packages/cspell-normalize-json/src/__snapshots__/fileObjects.jsonc
  packages/cspell-normalize-json/src/__snapshots__/index.test.mts.snap
  packages/flatpack-json/fixtures/cspell-cache-flatpack.json
  packages/flatpack-json/fixtures/cspell-cache-flatted.json
  packages/flatpack-json/package.json
  packages/flatpack-json/src/__snapshots__/Flatpack.test.mts.snap
  packages/flatpack-json/src/__snapshots__/Flatpack_fileList.json
  packages/flatpack-json/src/__snapshots__/Flatpack_fileList.jsonc
  packages/flatpack-json/src/__snapshots__/Flatpack_fileObjects.json
  packages/flatpack-json/src/__snapshots__/Flatpack_fileObjects.jsonc
  packages/flatpack-json/src/__snapshots__/storage.test.mts.snap
  packages/flatpack-json/src/__snapshots__/storage_fileList.json
  packages/flatpack-json/src/__snapshots__/storage_fileList.jsonc
  packages/flatpack-json/src/__snapshots__/storage_fileObjects.json
  packages/flatpack-json/src/__snapshots__/storage_fileObjects.jsonc
  packages/flatpack-json/src/__snapshots__/unpack.test.mts.snap
  packages/flatpack-json/src/__snapshots__/unpack_fileList.json
  packages/flatpack-json/src/__snapshots__/unpack_fileList.jsonc
  packages/flatpack-json/src/__snapshots__/unpack_fileObjects.json
  packages/flatpack-json/src/__snapshots__/unpack_fileObjects.jsonc
  packages/flatpack-json/src/flatpackUtil.mts
  packages/flatpack-json/src/index.test.ts
  packages/flatpack-json/src/optimizeFlatpacked.mts
  packages/flatpack-json/src/storage.mts
  packages/flatpack-json/src/types.mts
  packages/flatpack-json/src/unpack.mts
  pnpm-lock.yaml
Labels: fix
